### ISSUE TITLE
ODML Support

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#1]
This issue tracks the progress of ODML support.

**Comment by ferndot** [comment]
You can continue to work on this if you like, but I think we should ship "Ignition" with just plain text and html :)

**Comment by ferndot** [comment]
**Proposal:** Having a new format to define and support seems a little pointless now that I have thought of it.  Maybe we could just have meta tags giving document information and keep the rest of html (except scripts ofc).

The files could still be saved as .odml files.

**Comment by HR** [comment]
This doesn't make it unique as a format, it is just another .html and besides we have to make people aware of .odml our format for future use by other applications(third-party).

**Comment by HR** [comment]
Are we going to still support this in the future or not?

**Comment by ferndot** [comment]
I don't think so, closing.

A new format wouldn't make it, and would just complicate things...
