### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by logan-r** [codexa/firetext#10]
Will the HTML and ODML documents use CSS for styling?

**Comment by ferndot** [comment]
I added a commit that will make it style with spans that have a style attribute on them.  I think that will be easier than using formatting elements.

https://github.com/Joshua-S/FireText/commit/f8dbb7f4fde8b9d92e8e8baafedc1d82c1f1cade is the commit.
See https://developer.mozilla.org/en/docs/Rich-Text_Editing_in_Mozilla for info on the way that I am implementing the editor.
