### ISSUE TITLE
Dropbox checked by default and when window closed(crossed) switch still enabled

### ISSUE THREAD

**Issue by HR** [codexa/firetext#101]
Just two minor mistakes:
- [x] Dropbox shouldn't be checked by default
- [x] When you cancel Dropbox Auth by closing(crossing) the Auth window, the Dropbox switch shouldn't be enabled(switch should be off).

**Comment by ferndot** [comment]
The second issue is valid, and I will work on it ASAP.  The first issue is not correct...Try re-installing the simulator and see.

**Comment by ferndot** [comment]
Actually, just thinking about this.  If Dropbox is enabled, it will prompt the user to authenticate every time they open Firetext.  If a user enabled Dropbox when the connection was down, it would just wait until there was a connection and prompt them.  I think that this is good behavior.
