### ISSUE TITLE
Implement New UI

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#102]
@HRanDEV made some awesome mockups for Firetext at https://www.dropbox.com/sh/m19xkjll686mxmv/DliJBtGxqy
Here is the Design Spec/documentation
https://www.dropbox.com/s/4qfcjlvndirk3kv/maindesign.png
I am going to be implementing them!

**Comment by HR** [comment]
I am not finished with drawer yet(was ill last few days) and the edit mode I have to work on.
But the main is the final one for the home/welcome screen.

**Comment by ferndot** [comment]
Yes, here I go!!!

**Comment by HR** [comment]
Wait, give you the hex codes for colors of elements

**Comment by HR** [comment]
About design: It is a totally simplistic design which means that are are  no gradients involved and there is a design colour pattern in the ui (same colour for similar elements)

**Comment by HR** [comment]
Finally after about 2h work I have finished the Design Spec/documentation
https://www.dropbox.com/s/4qfcjlvndirk3kv/maindesign.png

**Comment by ferndot** [comment]
@HRanDEV +1!!!

**Comment by ferndot** [comment]
I think that we are done with this!

The enhanced workspace has its own bug, and the sidebar will wait until we have the collaborative API.
