### ISSUE TITLE
Navigation to menu won't trigger in chrome

### ISSUE THREAD

**Issue by jackd1** [codexa/firetext#103]
In chrome, the menu won't open if the span menu icon is clicked because the target will be the span icon.  A possible solution to this is would be to call processActions with the same eventAttribute argument but the targets parent for the target argument if there is no attribute named eventAttribute.  As far as I can tell it shouldn't cause any problems, but reply if it does, also, I can't really tell what lines 883-891 do.

**Comment by ferndot** [comment]
Thanks for catching this, since I just added desktop support, I haven't tested on Chrome.  Lines 883-891 do what you said, but by a different (and more buggy method).  I will change it!

**Comment by jackd1** [comment]
Ok.
