### ISSUE TITLE
Implement edit mode on long pressing a doc

### ISSUE THREAD

**Issue by HR** [codexa/firetext#104]
To make the app more intuitive we are going to change the default app call to enable edit mode (clicking button) to long pressing a document from the doc list which will also select the doc that is being tapped.

**Comment by logan-r** [comment]
Good idea!

**Comment by HR** [comment]
I think that long press is an ongoing touch:
https://developer.mozilla.org/en-US/docs/Web/Guide/DOM/Events/Touch_events?redirectlocale=en-US&redirectslug=Web%2FGuide%2FTouch_events#Finding_an_ongoing_touch
