### ISSUE TITLE
Cross-Platform Browser support

### ISSUE THREAD

**Issue by HR** [codexa/firetext#107]
We need to add full Cross-Platform Browser support for the Firetext WebApp (branch: master) so that it fully works in android, iOS and other Mobile OSes browser. The functionality can be made cross-platform by using Filesystem API (status: http://caniuse.com/filesystem).

**Comment by ferndot** [comment]
+1!

I am closing because we can't really track all of this.

**Comment by ferndot** [comment]
Just need to keep it in mind
