### ISSUE TITLE
Error: Permission denied to access property 'document' & Error: frame is null

### ISSUE THREAD

**Issue by logan-r** [codexa/firetext#11]
I can't type anything into the document.

**Error: Permission denied to access property** is from `editor.contentWindow.document.designMode = "on";`  (even if I comment this line out I still get the second bug)

and **Error: frame is null** is from 

```
frame.wrappedJSObject.getVisible().onsuccess = function gv_success(evt) {
  if (!evt.target.result) {
    request.cancel();
    return;
  }

  self.delegatePrompt(request);
};
```

**Comment by ferndot** [comment]
I have fixed that locally, just testing a few things before I commit it :)

**Comment by ferndot** [comment]
Fixed (I think) by https://github.com/Joshua-S/FireText/commit/6c21988ad38febdcce78a553352a963d02baa860
