### ISSUE TITLE
Add support for Android Mobile & Tablet Firefox Browser

### ISSUE THREAD

**Issue by HR** [codexa/firetext#111]
Eventhough we are going to make a cross-browser web app for Firetext, we need importantly currently need support for the Android Mobile and Tablet Firefox Browser. The whole web app infrastructure is going to be different and abstract from the Firefox OS Web App.

**Comment by HR** [comment]
@Joshua-S Can you do this please?

**Comment by ferndot** [comment]
Yes, but I don't know java.  Also, the online version may need to be split eventually because of differences in the way you do things, and code weight.

**Comment by HR** [comment]
You do not need to know java it is not native, it is the same stuff (html, css, js) 
https://support.mozilla.org/en-US/products/mobile/get-started

**Comment by ferndot** [comment]
Oh, I thought you were meaning for me to make a native Android app :)

**Comment by ferndot** [comment]
This is supported with Desktop.  Unless you want a new UI.
