### ISSUE TITLE
Firetext Web App Development

### ISSUE THREAD

**Issue by HR** [codexa/firetext#112]
This is a continued from #80. This issue is rather a discussion about the infrastructure of the Firetext Web App that is going to lay out the blueprint for the final product. There are some initial decision or question that we need to address before further development:
What server-side language will we use for the Backend?(python, php, ruby or even javascript)
We are choosing **JavaScript**
What framework will we use (if)?(Django, Phalcon, Ruby on Rails or Node.js)
We are using **Node.js**(http://nodejs.org)
How will we implement the user accounts system?
How will we implement the Client-Server Communication (DB) Workflow (#77)?
What kind Database will we use?(Compatibility of Client DB with Server DB is vital)
How will we track user changes/commits/comments?(locally then back to server)
We need to plan the whole App Workflow.
If there is anything I missed then add it to the list.I you have any then post your proposals how it should be. Else post about how we would go on about answering those questions, what is the starting plan?

**Comment by HR** [comment]
For now we are choosing Node.js as our framework (#115)

**Comment by ferndot** [comment]
I am assuming that Node.js will only be our framework on the web version.  Native apps will have to be plain javascript.

**Comment by HR** [comment]
No, there are plenty of framework available that allow web apps to work in native environments

**Comment by ferndot** [comment]
This is not relevant anymore.
