### ISSUE TITLE
Problems adding event listener on sandboxed editor

### ISSUE THREAD

**Issue by jackd1** [codexa/firetext#114]
In the browsers I've tested (chrome and opera), you can't edit a file because the event listeners that update the raw data aren't executed and produce an error because they are considered scripts executing in the context of the sandboxed iframe (editor) and the iframe doesn't allow scripts.  Unfortunately, I'm not sure what to do besides add allow-scripts, but that would defeat the purpose of it being sandboxed.

**Comment by ferndot** [comment]
Yes, this is a bug I found as well :(

Should we un-sandbox it, or look for a workaround?

**Comment by jackd1** [comment]
Well obviously it would be preferable to keep it sandboxed and find a workaround (we wouldn't want users opening a malicious file which executes a script and steals all their Firetext data).  We could update the raw data when switching tabs and saving, but we still can't autosave with that solution, another possible solution would be to remove allow-same-origin and add allow-scripts and just communicate with messages.  Other than those two and just not sandboxing the content, I can't think of any other workaround.

**Comment by ferndot** [comment]
I have checked out a lot of other html5-based editors, and none of them use sandbox on the iframe.  I think that the iframe in itself is good enough to sandbox it.  Can someone please try to hack it without the attribute.

**Comment by jackd1** [comment]
A user could recieve an HTML document with this text in it `<img src="https://www.google.com/images/srpr/logo11w.png" onload="console.log('you've been hacked')" />`.  If the user opens it in firetext, it will log `you've been hacked` to the console.  Obviously that doesn't amount to much, however the hacker could write any code they wanted in the onload event and execute it on firetext.  I've also found a security hole on [Line 356](https://github.com/Codexa/Firetext/blob/master/scripts/firetext.js#L356), when we create a div to get the text from, and insert the text, it executes any the script.

**Comment by ferndot** [comment]
Uhm, the first problem is not valid with the sandbox (which I am keeping btw).  The second is a security hole in the preview sanitizer that needs to be fixed ASAP!

**Comment by ferndot** [comment]
@jackd1 thanks for that!

**Comment by ferndot** [comment]
@jackd1 do you think that we could use [this](https://developer.mozilla.org/docs/Web/API/window.postMessage) to bypass the sandbox problem?

**Comment by jackd1** [comment]
That should work.  We will need to add allow-scripts and remove the allow-same-origin, I'll need to find a solution for the docx editor since it requires direct access to the origional dom.  A hacker will still be able to do slightly annoying things, like show JavaScript pop-ups, but that's not a big deal.

**Comment by ferndot** [comment]
Any way to block the showing of popups?

**Comment by jackd1** [comment]
Actually, now to think of it, I can override the alert, confirm, etc. functions.  Scripts can still modify the document (not the actual app though).

**Comment by ferndot** [comment]
@jackd1 one more question: is that okay?  Do you think users would consider that a feature or a security breach?

**Comment by jackd1** [comment]
Well we could call it a feature, but it does have some slight security concerns with phishing.

**Comment by jackd1** [comment]
Weird......your post isn't showing.  Anyway, xhr will fail every time
because without allow-same-origin, it has a unique origin.

**Comment by ferndot** [comment]
So phishing is not a huge threat...  Do you want to take this, or should I?

**Comment by ferndot** [comment]
There will need to be a special script to run in the iframe.  It will post messages for things like input, and we can send formatting commands to it.

**Comment by jackd1** [comment]
I can work on this.

**Comment by jackd1** [comment]
As far as I can tell, my latest commit: 9af0ede, has fixed this (although there is still a security bug which I need to fix, but it shouldn't be very hard).  @Joshua-S, @HRanDEV, @logan-r Can you guys think of anything I missed?

**Comment by jackd1** [comment]
I missed hyperlink functionality.  (Just a reminder to myself)

**UPDATE:**  This was fixed by 8439d317762e5d2ebbe01d013443359a0e7723fd

**Comment by ferndot** [comment]
Great!  Now let's just hope gecko implements this soon.

**Comment by jackd1** [comment]
Ok, I'll mark this fixed after I fix that security bug then.

**Comment by jackd1** [comment]
@Joshua-S I just added a polyfill for message channel, so I can merge this now while we wait for firefox os to support it natively.

**Comment by ferndot** [comment]
Great work.  Save isn't working for me though...  I will look at the code, and see what can be done :)

**Comment by jackd1** [comment]
Ok, hopefully it's not hard to fix.

**Comment by jackd1** [comment]
Found the problem, I couldn't transfer a blob, so I'm using a binary string now (857a53892ed62d630c1b9daf922334987b8ec3f0)

**Edit:** I changed it to a base64 string to fix some problems (954beeed5b6b7b56e6b9685f198e4d2fb64f5d4b)

**Comment by ferndot** [comment]
@jackd1 :+1:
