### ISSUE TITLE
Web Views

### ISSUE THREAD

**Issue by HR** [codexa/firetext#116]
We have to create node views (layouts) using the node template engine **jade**(http://jade-lang.com/), we need the following views:
Drawer
Main
Edit Mode
Settings
Open/Create Doc
Auth views

**Comment by ferndot** [comment]
I am developing this on Cloud 9.

**Comment by HR** [comment]
ok, but let me just set up the workspace

**Comment by ferndot** [comment]
Oh, I started already (yours wasn't cooperating).

https://c9.io/joshua-s/firetext

**Comment by ferndot** [comment]
We don't need this bug to track anymore :)

**Comment by HR** [comment]
No, we need this for the webapp

**Comment by ferndot** [comment]
Closing because we aren't working on the node app anymore.
