### ISSUE TITLE
Implement: New Enhanced Editor Workspace

### ISSUE THREAD

**Issue by HR** [codexa/firetext#118]
This issue is explicitly for the new workspace integration

**Comment by HR** [comment]
@joshua-s have you started this?

**Comment by ferndot** [comment]
I will :)

**Comment by HR** [comment]
how is this going on @Joshua-S , finished?

**Comment by ferndot** [comment]
Not yet, I want to ship a performance fix (0.3.1) ASAP.  I will push some changes to a new workspace branch soon.

**Comment by ferndot** [comment]
Starting work on this!

**Comment by HR** [comment]
:+1:

**Comment by HR** [comment]
When are you finishing with new UI?

**Comment by ferndot** [comment]
Implementation started: #312

**Comment by ferndot** [comment]
A new, more expandable toolbar was implemented. It followed different specs.
