### ISSUE TITLE
Creating a document

### ISSUE THREAD

**Issue by HR** [codexa/firetext#12]
Hey when will you add the ability to create a new .odml, .txt or .html?(from the interface)

**Comment by ferndot** [comment]
We are working on it, but we need to be able to save/open files first :D

**Comment by logan-r** [comment]
@Joshua-S Saving and loading files works, as long as the files are in the recent list. (But we still need a way to open new files)

**Comment by ferndot** [comment]
There is no native file browser in Firefox OS, so I think we will have to get (enumerate) all files in the documents directory, and display them as a list.

**Comment by ferndot** [comment]
Done!  Sorry if you were planning to do this @Logi0 :(
