### ISSUE TITLE
Fix Require JS

### ISSUE THREAD

**Issue by HR** [codexa/firetext#124]
Issue explicitly for fixing all errors in require js

**Comment by HR** [comment]
@jackd1 can you do this please?

**Comment by jackd1** [comment]
Yes, I'm currently working on a solution.

**Comment by HR** [comment]
:cool:

**Comment by HR** [comment]
Any Idea when you @jackd1 will finish?(approx. time period) 
Because as you know there is loads of to be added and tested.

**Comment by jackd1** [comment]
Unfortunately, I'm not really sure.  I've been very busy lately, I haven't been able to use a real computer since Monday.

**Comment by HR** [comment]
Can you maybe find time just to fix this?

**Comment by ferndot** [comment]
@HRanDEV I will fix it if @jackd1 doesn't have time.

**Comment by HR** [comment]
Thanks, I currently too lack time

**Comment by ferndot** [comment]
I am moving this to milestone four because we _really_ need to release 0.3.

We can develop RequireJS in a branch specifically for it, we need to keep the master branch stable and functional.

**Comment by ferndot** [comment]
Not valid anymore!

**Comment by HR** [comment]
we'll do this in v0.4 for security

**Comment by ferndot** [comment]
But this isn't the right issue.  There is another "Implement requireJS issue."

**Comment by HR** [comment]
k
