### ISSUE TITLE
Enable page element transfomation

### ISSUE THREAD

**Issue by HR** [codexa/firetext#127]
We have to allow users to scale page elements such as images, tables, etc.

**Comment by ferndot** [comment]
I am going to work with the Midas team on this =)

**Comment by HR** [comment]
Was about to talk to you about this

**Comment by HR** [comment]
BTW who is in the MIdas team?

**Comment by ferndot** [comment]
I don't know yet, trying to find out.

**Comment by ferndot** [comment]
This is a Mozilla issue, so closing.  When they fix it, this will be automatically enabled for us, no work needed on our side.
