### ISSUE TITLE
Keyboard does not appear when editing doc

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#13]
I think this is because I used an iframe.  Checking with the gaia devs...

**Comment by ferndot** [comment]
Filed bug 866270 to implement keyboard hiding/showing.

See: https://bugzilla.mozilla.org/show_bug.cgi?id=866270

**Comment by ferndot** [comment]
The gaia team is a little slow :(

This is the last blocker bug that we need to fix before shipping 0.1!

**Comment by logan-r** [comment]
The keyboard works fine for me! (or maybe I just don't understand the bug)

**Comment by ferndot** [comment]
The virtual keyboard doesn't show.  On the computer it is ok because you can use your hardware keyboard.  Smartphones don't usually have one.

**Comment by logan-r** [comment]
Hmmm... I was referring to the virtual keyboard...

**Comment by ferndot** [comment]
Really?  What is your version of Firefox OS?

**Comment by logan-r** [comment]
1.0.0.0-prerelease

**Comment by ferndot** [comment]
I have 1.1 prerelease.  Do you have a device or desktop, or are you using the simulator?  Maybe its a simulator bug...

**Comment by logan-r** [comment]
I'm using the simulator.

**Comment by logan-r** [comment]
Maybe you could call `doc.focus()` or `doc.blur()` (`doc` is `editor.contentDocument.body`).

**Comment by ferndot** [comment]
This bug will fix it:
https://bugzilla.mozilla.org/show_bug.cgi?id=811177

I don't know the time-frame though, so I am going to try a workaround for v.0.1.
