### ISSUE TITLE
Performance boosters

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#130]
All the new features we are implementing are causing Firetext to feel very laggy.  We need to improve the performance.  Ideas for boosters go below.
- [x] Convert all the svgs to a single icon font.
- [x] Optimize css.

**Comment by jackd1** [comment]
I've been working on the workers, however I just discovered getDeviceStorage does not appear to be available to Web Workers.  (requestFileSystem is however)

**Comment by ferndot** [comment]
We just need to use workers for all possible things.  E.g. Settings.

**Comment by jackd1** [comment]
I looked through the code, and there is literally nothing that I can port to a web worker besides the FileSystem IO, which is a problem since device storage isn't supported by web workers.

**Comment by ferndot** [comment]
Okay :(

**Comment by ferndot** [comment]
The editor frame wasn't working either.  The font changes made it a lot faster though.  We can ship this soon as version 0.3.1.  Users will be so happy :)

**Comment by ferndot** [comment]
All done!  Performance gains are huge on mobile devices!
