### ISSUE TITLE
Sanitize preview html

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#132]
We need to sanitize the html before it is injected into our description field.  Unsanitized html causes performance issues, and is a security vulnerability.

Fix this ASAP!

**Comment by asdf23** [comment]
Test case:
Create a new document
Name the document <u>FileName</u>
Click Create
View the file name. The file name should not have an underline applied to it

**Comment by asdf23** [comment]
It seems very likely that we may want to push this file to another computer/service/fat32 so I think we should consider restricting the valid input. I found this page on the subject: http://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx 
Beyond some special characters also to avoid are some strings such as LPT1, COM4, two consecutive periods.
Not sure how far we want to take this, perhaps avoiding special characters is enough.

**Comment by ferndot** [comment]
@asdf23 thank you for this, I honestly never thought about it.  Could you open a new issue for "File name sanitization" please?

**Comment by asdf23** [comment]
If so I missed the point of this bug. I've uploaded a crude fix for it in buttons... well I think I did. Should I think of branches as my own little world or should I think of 1 branch ~= 1 bug?
Also could you give a little more detail on this bug?

**Comment by ferndot** [comment]
You should do 1 branch per bug so that it is easier to review your Pull Requests.

This bug is about removing all elements and styling from the html before displaying it above the file name in the "Recents" section.  Right now, certain files can superimpose themselves on the UI.  Another way that I am thinking of doing it is using an iframe to display previews.

**Comment by asdf23** [comment]
I think it should be possible to just display  .innerText

**Comment by ferndot** [comment]
You mean textContent?  That is what we used in previous versions, but it is not really a good preview.  We want to show italics, bolds, lists, tables, and images in the preview.

**Comment by asdf23** [comment]
I was unaware of textContet..
In htmlPreviewSanitize I'ved added a function to clean up a text file. It will force a single line and width in characters, adjusting that width to the nearest space before or after. I think I can use the same or similar method for HTML and then reapply the formatting without breaking the HTML code...

**Comment by ferndot** [comment]
Where are your changes?

**Comment by ferndot** [comment]
Just fyi, the easiest way to keep your fork up to date is to do this in the Terminal (or command prompt):

```
git remote add codexa https://github.com/codexa/firetext.git
git pull codexa master
```

**Comment by asdf23** [comment]
Changes are here: 
https://github.com/asdf23/Firetext/commit/e337a412e02ea22d9fc7c8a749c5dfc5ca3c09f2
these are not ready to be included back to the main branch

**Comment by ferndot** [comment]
Thank you for working on this :)

**Comment by asdf23** [comment]
I've made another update. Here's how it works: The preview for a text document is set at some arbitrary width in characters. The nearest space before or after that point is sought and if found used if not found a string "..." is appended at the cut off point. HTML works in a similar way. HTML is converted to text, this same method is used to find a truncated text string. This string  is used to generate a regexp to find the corresponding point in the original HTML, the actual truncation occurs before the next non-closing tag. Next some tags are stripped out (hr, br, img) - probably more are needed. Next the html is closed. Meaning that since the truncation point is found after the first non-closing tag after the desired text cut off point the entire HTML at this point would not have been properly closed.  Next all tables of multiple rows are converted to tables of a single row. Thus making a single line of HTML of the same approx size as the text preview.

**Comment by ferndot** [comment]
Woah, genius!  I can't wait to test this on Monday.

**Comment by ferndot** [comment]
Is this ready?  If it isn't, I'll just do a quick (hacky) fix by putting the previews in iframes.

**Comment by asdf23** [comment]
There is somde debug code that needs to be removed. I will be unavailalbe
for a few days have some family emergency stuff I need to deal with. Sorry
about the inconvenice. All I would do at this point is to remove the
debugging code. well and test lots of sceniross

**Comment by ferndot** [comment]
It's not a problem, just hope that the emergency is resolved.  They can be very emotionally stressful.

**Comment by ferndot** [comment]
I will quick-fix this tomorrow.  Moving the advanced preview sanitizer to another bug.

**Comment by ferndot** [comment]
Fixed by https://github.com/Codexa/Firetext/commit/7d341b1d2fe5deca696ccfbe51a13b9ec20a206a

**Comment by ferndot** [comment]
Note: There is one bug that needs to be fixed before shipping.
