### ISSUE TITLE
When deleting a file misalignment issue

### ISSUE THREAD

**Issue by asdf23** [codexa/firetext#137]
When I try to click a radio button to delete a file. It seems I have to click a little above the radio button.

**Comment by ferndot** [comment]
Is this on a device or on the Simulator?  The Simulator has always had trouble with this, but (my device at least) is fine.

**Comment by asdf23** [comment]
Yes on the simulator. I'm still waiting for my Peak+ to arrive. The CSS associated with this seems to be outside of Firetext

**Comment by ferndot** [comment]
I will close it then, and if the problem occurs, we can re-open it.
