### ISSUE TITLE
Need feedback for direction of project.

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#14]
Hello, I have been thinking that implementing odml/html is getting a little buggy and is slowing down the progress of the project.

@Logi0, @HRanDEV, what do you think about making FireText (the first version at least) only support plain text.  We could add it later once we have basic functions (open, save, etc..) implemented.

**Comment by HR** [comment]
I have an idea of implementing cloud service APIs such as google drive, dropbox and skydrive

**Comment by ferndot** [comment]
That sounds cool!

**Comment by HR** [comment]
You know, next generation apps rely on cloud backup services and other social stuff

**Comment by ferndot** [comment]
I agree!

So should we put aside html + odml for now?

**Comment by HR** [comment]
yes, after completing the completely basic structure (creating files,...) and then try to support .doc or .docx because LOADS of people use this file extension and there are apps in android that offer this support (in java) and so we need that support for it to be a success.

**Comment by ferndot** [comment]
+1

@Logi0 what do you think?

**Comment by logan-r** [comment]
I vote against doing so, because html already works and odml is close to working. Also, I think we should support .rtf documents (they're easier to handle than .doc or .docx, but still supported by Word and almost everything else)

**Comment by ferndot** [comment]
Should we at least de-activate them to ship version 0.1, or should I extend the due date?

**Comment by HR** [comment]
Take it slow with the formats since it firefox hasn't been released to consumers and rather work on completing the basic functionalities and features.

**Comment by logan-r** [comment]
Maybe just html and txt for version 0.1?

**Comment by ferndot** [comment]
That sounds good, @HRanDEV?

**Comment by HR** [comment]
yeah, just html and txt for v0.1

**Comment by ferndot** [comment]
Closing!
