### ISSUE TITLE
Localize Firetext

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#140]
Localizations are available at: https://www.transifex.com/projects/p/firetext

**Comment by HR** [comment]
Firstly, where has FxOS been released?

**Comment by ferndot** [comment]
I can't remember all the places off the top of my head, but I know it has been released in Poland, Spain, Venezuela?, Brazil, Africa (soon), and other emerging markets.

Currently, Firefox OS supports English, Spanish, and Portuguese (that's why I marked them critical).

**Comment by logan-r** [comment]
Is this something that google translate could solve or do we need to get someone fluent in each language to translate it?

**Comment by ferndot** [comment]
I was thinking of doing something like this: https://hacks.mozilla.org/2013/08/localizing-firefox-os-apps/.  And Google Translate is pretty good for short things, but when we get a community going, a real person would be best of course :)  Google Translate will have to do for now though.

**Comment by jackd1** [comment]
I may be able to help out with the Spanish translation, I'm in Hon. Spanish 2 at my school, so I can translate some simple to medium complexity parts.

**Comment by ferndot** [comment]
Great @jackd1!

**Comment by ferndot** [comment]
I am integrating l10n now :)

**Comment by HR** [comment]
I'm fluent in german, so I can translate about any level of complexity

**Comment by ferndot** [comment]
Please create a user on Transifex (https://transifex.com/)

**Comment by HR** [comment]
Done, join in at https://www.transifex.com/projects/p/firetext/

**Comment by HR** [comment]
we're at https://www.transifex.com/organization/codexa

**Comment by ferndot** [comment]
Uhm...  Mozilla was creating a project for us.  That way, we would get more translators from the Mozilla localization team.

**Comment by ferndot** [comment]
This is specifically a translation program.  But it would increase the publicity of the project.  Anyway, they can get it translated into a lot more languages than we can alone.

**Comment by HR** [comment]
y, but can can you just do some PR and get some advocates to work on it?

**Comment by jackd1** [comment]
Btw, is this only for the app, or the website to?

**Comment by ferndot** [comment]
@jackd1 this is for the app.  Mozilla has an apps translation program to expand developers' reach.

**Comment by ferndot** [comment]
See: https://hacks.mozilla.org/2014/01/localizing-the-firefox-os-boilerplate-app/

**Comment by jackd1** [comment]
Ok, thanks.

**Comment by ferndot** [comment]
Should be ready now!

**Comment by jackd1** [comment]
@Joshua-S Great :+1:

**Comment by ferndot** [comment]
I am going to implement the language change function.  Also, a first time experience with languages.  The localization file is uploaded to Transifex (that work goes on separately).

**Comment by ferndot** [comment]
Selection done here: https://github.com/Codexa/Firetext/commit/12cfb79b6a18395a31880b8953bd477ffc71f655!  Now, as soon as we get the languages, we can add them to the repo and enable the corresponding option.

**Comment by bdcomp** [comment]
Hebrew translation almost done.

Although I am not sure how to translate string with html tags, as it's garbled while RTL...

**Comment by ferndot** [comment]
@bdcomp: Thank you for your awesome work!  I will add you to the [credits page](http://firetext.codexa.org/community/credits/) soon (need to get it working with Transifex).  Also, we were not anticipating RTL languages when we initially coded Firetext.  I need to rework some of the CSS (#165).  

About the html tags (I am assuming you mean the `<b>`'s).  You can leave them out if it doesn't work with Hebrew.  I used them to highlight the main idea of the settings (e.g. Interface **language**).

**Comment by ferndot** [comment]
Spanish (es) and French (fr) added in https://github.com/Codexa/Firetext/commit/3b87427334a88bc3cc79dbc2c7398b6d7695f8c2.  Please test to see that they read right!

I may need to do a few styling updates.

**Comment by ferndot** [comment]
Hebrew (he) added!  Many thanks to @bdcomp and the other translators.

Note: Issue #165 needs to be fixed before shipping Hebrew.

**Comment by ferndot** [comment]
Portuguese, Polish, and Czech are now finished.  I will add them soon!

**Comment by bdcomp** [comment]
According to Mozilla [1], Firefox OS will expand this year to: Argentina, Costa Rica, Ecuador, El Salvador, Germany, Guatemala, Nicaragua, Panama, Croatia, Czech Republic, Macedonia and Montenegro.

To make sure we are ready to launch in this countries, please add the missing languages: Croatian, Macedonian and Serbian.

[1] https://blog.mozilla.org/blog/2014/02/23/firefox-os-unleashes-the-future-of-mobile/

**Comment by Ryuno-Ki** [comment]
The Firefox OS is already available in Germany ;-)

Alcatel OneTouch Fire is shipped by Congstar (a subsidiary of Deutsche Telekom) here. Sadly, only Fx OS 1.1, since Alcatel opted to skip v1.2 (which blocks app development … but that's another topic).

**Comment by ferndot** [comment]
@bdcomp done!  Thanks for researching this for us :)  By the way, I almost have RTL done for Hebrew.

@Ryuno-Ki aren't they going to ship with 1.3 eventually though?

**Comment by ferndot** [comment]
We may be moving translations into a branch so we can ship them sooner than we were planning.

**Comment by Ryuno-Ki** [comment]
@Joshua-S They do. But the [App Manager](https://developer.mozilla.org/en-US/Firefox_OS/Using_the_App_Manager) requires Firefox 26+ and Firefox OS v1.2+. As far as I know it replaced the Firefox OS Simulator.

**Comment by ferndot** [comment]
Czech, Italian, Polish, and Portuguese (Brasil) were added in https://github.com/Codexa/Firetext/commit/3a66d09b45b50fead119b2314599c4e938d98bb8!

**Comment by ferndot** [comment]
We are going to move the new languages into a branch so that it can be released along with a Hacks post this/next week!

**Comment by ferndot** [comment]
Two more minor bugs, and we can ship!  The language branch is https://github.com/Codexa/Firetext/tree/0.3.2.

**Comment by ferndot** [comment]
Fixed!  @bdcomp is it possible for you to take a brief look at RTL styling to make sure it's okay?  None of us know a RTL language, so it is a bit difficult.

You can download it to your computer and use the Tools > Web Developer > App Manager, or push it to a device, or use http://firetext.codexa.org/app in your web browser in Responsive Design Mode with Dropbox at 320x480px.

**Comment by bdcomp** [comment]
@Joshua-S I tested the app on Firefox OS Simulator.
Beside my tiny translation change, Hebrew interface looks great.
Good job!

I am not sure how to create a new file on the Simulator (unknown error), so editing not tested.

**Comment by ferndot** [comment]
@bdcomp thanks!  That unknown error is because the Simulator does not support DeviceStorage anymore, but `window.navigator.getDeviceStorage()` is still present.  That causes Firetext to think it exists, and error when trying to use it.

The Turkish issue was fixed in https://github.com/Codexa/Firetext/commit/ac7fd7c156180684c3905f0b88960a21e7291769.  Thank you for reporting that.

**Comment by bdcomp** [comment]
@Joshua-S By "my tiny translation change" above, I mean the Hebrew translation I just updated.
Just to be sure you will pick it up before releasing 0.3.2

**Comment by ferndot** [comment]
Will do!  Is it possible for you to review the changes so that I will receive the correct ones?  E.g. When I download the translation file, it might give me any of the possible translations for strings that aren't reviewed...

**Comment by bdcomp** [comment]
Done.

**Comment by ferndot** [comment]
Thanks!  I will upload the changes with the localized manifest.  Could you please post one more change to the manifest_properties resource?  (A translation for "The word processor for Firefox OS")

**Comment by bdcomp** [comment]
Done!

**Comment by ferndot** [comment]
The next version has been uploaded to the Marketplace, and is pending review.  Great job all :)

<b>(03/07/14) Update: </b>Firetext 0.3.2 is now publicly available!

**Comment by ferndot** [comment]
A contributor on Transifex requested a Hindi (India) translation.  It has been added.

There is now a place on our [Credits Page](http://firetext.codexa.org/community/credits/) for localizers.  Thank you for all your hard work!  If you have contributed translations, and have not been added to the list, please tell me (we have to add people manually to it at this point, so I may have unintentionally missed someone).

**Comment by ferndot** [comment]
Bengali (Bangladesh), Chinese (China), and Dutch (all requested by contributors on Transifex) are now complete.  I will be uploading them soon.

**Comment by ferndot** [comment]
Romanian (ro) was just added.  Thank you Cristian Silaghi!

**Comment by ferndot** [comment]
Almost time for another language release...

**Comment by airon90** [comment]
As the Transifex account is open and information has been added in homepage, can we close this bug?

**Comment by ferndot** [comment]
I was leaving this bug open as a tracker for new languages added.

**Comment by airon90** [comment]
Ok, so you should add Esperanto (eo) ;)

**Comment by ferndot** [comment]
Done!

**Comment by ferndot** [comment]
I am working on releasing an update containing the following locales:
- Bengali (Bangladesh)
- Chinese (China)
- Czech
- Dutch
- English (US)
- Esperanto
- French
- German
- Hebrew
- Indonesian
- Italian
- Polish
- Portuguese (Brazil)
- Romanian
- Russian
- Spanish

Note that soon we may not need to update every time locales are added.  Transifex Live will allow us to send new translations directly to app users.
