### ISSUE TITLE
Advanced sanitizer

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#141]
This was moved from Issue #132.  @asdf23 was working on an advanced and more expansible sanitizer for previews.

**Comment by ferndot** [comment]
Also fixed by: https://github.com/Codexa/Firetext/commit/7d341b1d2fe5deca696ccfbe51a13b9ec20a206a

Note: There is one bug that needs to be fixed before shipping.

**Comment by ferndot** [comment]
[update] I have only been able to re-create the issue with one file.  I think it is minimal enough to justify shipping without a fix.  What do you think?  Please respond ASAP. @Codexa @asdf23

**Comment by HR** [comment]
I think that it should be alright

**Comment by ferndot** [comment]
If someone objects, I'll take it down, but I am uploading it to the MozMarketplace now!
