### ISSUE TITLE
[Autosave] Save flooding

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#145]
Autosave is currently unreliable because it floods the internal storage with saves, causing errors and data losses.  We need to monitor file content, and then save it in intervals.  We auto save on file exit.

This may or may not apply to cloud.  If it does, the time lapses should be shorter.

**Comment by HR** [comment]
Should we cache it with indexdb?

**Comment by ferndot** [comment]
[update] I don't know why I said that we need to "cache" content...

In https://github.com/Codexa/Firetext/commit/b246651811e38902a515d561f66788639122ebd0, I introduced a new variable called `fileChanged`.  We can just check its value at regular intervals, and save if it is equal to `true`

**Comment by ferndot** [comment]
Quick fix for this as well!
