### ISSUE TITLE
SyntaxError: invalid quantifier

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#148]
``` bash
SyntaxError: invalid quantifier
```

**Comment by ferndot** [comment]
Yay, Bugsense works!  Anyway, this is a legit issue that I am seeing in https://github.com/Codexa/Firetext/blob/v0.3/scripts/firetext.js#L343.

**Comment by HR** [comment]
So is this occurring in the file name validation function?

**Comment by ferndot** [comment]
I haven't seen this in a while, so closing.
