### ISSUE TITLE
SyntaxError: unmatched ) in regular expression

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#158]
``` bash
SyntaxError: unmatched ) in regular expression
```

**Comment by HR** [comment]
Which line? and why are we trying to match ")" (for what?)

**Comment by jackd1** [comment]
I believe that means that there is an opening parenthases ("(") but no closing one (")").

**Comment by HR** [comment]
Is that using when creating a regex object with construct method (new Regex())
