### ISSUE TITLE
Autosave on input rather than delay.

### ISSUE THREAD

**Issue by jackd1** [codexa/firetext#164]
Currently, autosave is saving every second, but we are already monitoring the input event, so would you guys like me to change it so that it only saves on input?

**Comment by ferndot** [comment]
@jackd1 I am a bit confused at what you are meaning.  Basically, what we currently do is wait for input, and then save.  Input tends to happen in large amounts over a short period of time however.  This can cause errors if the program opens a new write before the previous one is finished.  The current script waits for input, and then saves.  If a previous save is in progress, it waits until it finishes before saving, and if the input is constant, it saves in intervals of 1 second to avoid flooding the memory.

**Comment by jackd1** [comment]
@Joshua-S, Ok, I got it, I misunderstood the code.  It took me a minute to figure it out.  Thanks.
