### ISSUE TITLE
Support RTL languages

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#165]
To support languages like Hebrew, we need to redo the stylesheets to support RTL layout.

**Comment by bdcomp** [comment]
@Joshua-S May I translate for now the remaining strings with html bold tags, by just removing the tags?

**Comment by ferndot** [comment]
Of course!  They were just a minor visual aid that I am starting to regret because of localization issues.

**Comment by bdcomp** [comment]
Hebrew translation done!

**Comment by ferndot** [comment]
:+1:

**Comment by ferndot** [comment]
In https://github.com/Codexa/Firetext/commit/5b045d0f9e8320568fefbd65d86ecb138ac262b0, I made the language function assign a `data-language` attribute to the`<body>`.  (may change that to add it to the `<html>`.)  It is now possible to customize the css for each language.  

Also, I am considering adding a `data-direction` attribute to make it easier to distinguish in the css between ltr and rtl languages.

**Comment by bdcomp** [comment]
Yay! I wanna try it :)

@Joshua-S How about to release a new version, as there were many languages/translations related commits since the last version?

**Comment by ferndot** [comment]
@bdcomp we are actually doing that :)  I am going to move the new languages into a branch so that we can release a new version this week.  We are also making a Hacks post that should come out next week (maybe Monday).
