### ISSUE TITLE
Line 368 using wrong string method.

### ISSUE THREAD

**Issue by jackd1** [codexa/firetext#167]
[Line 368](https://github.com/Codexa/Firetext/blob/master/scripts/firetext.js#L368) in firetext.js is clearly using the wrong string method (sub is for surrounding the text with a &lt;sub&gt; tag).  I meant to file this a while ago.  Does anyone know which method this should be?  (there are several slightly different string methods that this might be)

**Comment by ferndot** [comment]
Maybe `string.substring()`?  That is a common error.

**Comment by jackd1** [comment]
Probably either substring or substr.  They behave the same with one arg. though, I'll make a quick fix.
