### ISSUE TITLE
Firetext on Firefox OS Simulator 2.1 doesn't work

### ISSUE THREAD

**Issue by airon90** [codexa/firetext#177]
Firetext on Firefox OS Simulator 2.1 doesn't work:
- Trying to access to a non-existing SD card it returns an error: TypeMismatchError
- Trying to create a document it returns an error: Unknown

See readme.md to get the simulator

**Comment by ferndot** [comment]
This issue actually does not occur on a device, only the FF Simulator.  Although, if you could find the cause, we would be very thankful!

This bug may or may not be related: https://bugzilla.mozilla.org/show_bug.cgi?id=996619

**Comment by ferndot** [comment]
[Update] Apparently the sdcard is emulated on the simulator, but since it is empty by default, we return an error.  I will look into the code (https://github.com/codexa/firetext/blob/develop/scripts/io.js).

It does work when the fake-sdcard directory (see the bug) has contents.

**Comment by airon90** [comment]
I'm not worrying about SD emulation, I'm worrying about document creation! Did API changed from 1.x to 2.x?

**Comment by ferndot** [comment]
It changed several times, but so did we...  This is definitely a strange issue because it works fine on a device running 2.1.

**Comment by ferndot** [comment]
@Airon90, @twiss can you confirm that this is fixed?

**Comment by twiss** [comment]
I can create a document now, but I can't open it for some reason. It gets to "Finished loading modules/editor/editor.html" but nothing happens on screen.

**Comment by airon90** [comment]
I'm using latest Firefox OS 3.0 on Flame and I can create, edit and open both files, txt and html.

**Comment by ferndot** [comment]
We never receive an `init-success` message: https://github.com/codexa/firetext/blob/f75859a7d368565432d637fc6cf2ef8417dc802c/scripts/firetext.js#L711 on the Simulator. I wonder what is preventing message passing?

**Comment by twiss** [comment]
The scripts in the editor trigger `onerror`. I've pushed a solution which puts the script source inline to `simulator`, it's far from a pretty solution though.

**Comment by ferndot** [comment]
Can you make a PR please?

**Comment by ferndot** [comment]
Hmm, Firetext works without any issues in the Firefox OS 3.0 Simulator.
