### ISSUE TITLE
Dropbox integration.

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#18]
This issue is to track the process of Dropbox integration.  All issues related to that will be referenced here.

See this repo for help: https://github.com/dropbox/dropbox-js.

**Note:** I have moved dev to the 0.2 branch.

**Comment by ferndot** [comment]
I created an API account.  Please email me to get the _secret_ and _authid_.

**Comment by HR** [comment]
I need logi0 email to give him permission to see google drive api.

**Comment by ferndot** [comment]
This is the Google Drive issue: https://github.com/Joshua-S/FireText/issues/20.

@Logi0 can we have your email please?

**Comment by HR** [comment]
I need logo url please (png - 120x60 max)

**Comment by ferndot** [comment]
Ok, https://www.dropbox.com/s/10wvztz82t2a9x2/app_icon_large.png is the biggest one I have now.

**Comment by logan-r** [comment]
@HRanDEV My email is kai.ralston@gmail.com.

**Comment by HR** [comment]
You're in man! go to https://code.google.com/apis/console/#project:159910945560

**Comment by logan-r** [comment]
Thanks!

**Comment by HR** [comment]
What is the progress on this, have you fully implemented it yet?

**Comment by ferndot** [comment]
Not fully, I am having trouble with storing settings, so that is a little bit of a mess, also, auth is a little tricky...

**Comment by HR** [comment]
We can store all this data in indexedb later on under the User ID DB.

**Comment by HR** [comment]
For now just use localStorage if you can.

**Comment by ferndot** [comment]
Ya, the problem is, I _stink_ at localStorage.

**Comment by HR** [comment]
https://developer.mozilla.org/en-US/docs/Web/Guide/DOM/Storage

**Comment by ferndot** [comment]
The rest should be easy!

**Comment by ferndot** [comment]
@HRanDEV can you make a Dropbox document icon.  (Same style as the Firetext one, but with the Dropbox logo).

**Comment by HR** [comment]
ok

**Comment by HR** [comment]
send it

**Comment by ferndot** [comment]
Send what?

**Comment by HR** [comment]
I meant, I sent the dropbox icon

**Comment by ferndot** [comment]
Oh :)

**Comment by ferndot** [comment]
Another bug bites the dust!
