### ISSUE TITLE
[Language] Support auto language

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#180]
To follow the default settings for a Firefox OS app, we should add an "Auto" item to the language select.  This would be the default value.  The benefit of this option is that when a user changes the system language globally, it would also change the language of Firetext instead of them having to manually change it.

Thoughts anyone before I implement this?

**Comment by jackd1** [comment]
Sounds good, should be easy to implement.

**Comment by ferndot** [comment]
It was!
