### ISSUE TITLE
[Investigate] WebODF editor

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#189]
This issue is for research into using the WebODF (http://webodf.org/) editor in place of the browser-specific designMode editor.

I have heard that WebODF is very good with XML based languages, and it would be relatively trivial to add DOCX support as well as the integrated ODF support.

**Comment by twiss** [comment]
So, I've been trying out WebODF and as you know I do, I found some bugs. I don't want to drop all of them on the developers at once, but I've listed them in steno at https://gist.github.com/twiss/23f1cae09eab46202abc/efe3ccea8a515e97b6e7f2896131aa3d352b9c6d#file-todo-L164-L208.

Could you try out WebODF on Firefox OS? In particular, does backspace work?

**Comment by ferndot** [comment]
We are using our own editor for now: #261
