### ISSUE TITLE
[Editor] Implement better code editor

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#192]
We are in desperate need of a better code editor.

Potential editors:
- [Ace](http://ace.c9.io)
- [CodeMirror](http://codemirror.net/)

Feel free to suggest other editors.

**Comment by gbraad** [comment]
[CodeMirror](http://codemirror.net/) is another alternative which is very easy to implement

**Comment by ferndot** [comment]
CodeMirror has many features, and performs about the same as Ace from my tests. So, the implementer can choose which to use.

Would you like to fix this issue? I can provide guidance.
