### ISSUE TITLE
Reorganize top bar buttons

### ISSUE THREAD

**Issue by twiss** [codexa/firetext#196]
For consistency, would it be an idea to in all screens, put the menu and menu button on the left (in zen mode, that would mean to the left of the Design and Raw buttons) and zen mode/close on the right?

**Comment by ferndot** [comment]
I like the focus on consistency. The only caveat to this approach is that the close button is usually expected to be the left-most button (similar to the back button), and the menu button is also expected to be flush with the edge of the view.

**Edit:** in zen mode, the close button is on the right. What would you do for regular (non-zen) mode?

Could you send me a simple drawing of how this would look?

Thank you again!

**Comment by twiss** [comment]
You're probably right that you should stick with the close button on the left. So here's what I meant but with close and menu swapped:
![firetext-header](https://cloud.githubusercontent.com/assets/908303/4899927/23945168-6421-11e4-854c-6944b5cc2277.png)

If you want to see it the other way around too, just ask.

**Comment by ferndot** [comment]
:+1: I just looked through a few of the gaia default apps, and it looks like they are moving towards the menu-on-the-right pattern. They also have a new menu icon (looks like •••) that we could use.
