### ISSUE TITLE
URI.js unnecessary

### ISSUE THREAD

**Issue by twiss** [codexa/firetext#198]
This is not a user-visible bug, but might be worth investigating anyway.

In https://github.com/codexa/firetext/blob/0f43b6a6/scripts/editorLoader.js#L22, URI.js requires a trailing slash (`"editor/"`) to recognize `editor` as a directory instead of a file. The reason it works is because `.src` returns an absolute url. In other words, you won't break anything by replacing everything with `scriptTags[i].src` and removing the URI.js library.

Correct me if there's something I missed, of course.

**Comment by jackd1** [comment]
I believe that is supposed to be the case, but I feel like I remember trying that, and having issues with some implementations which did not do it that way.  Could you possibly do some tests to confirm or deny this?

**Comment by twiss** [comment]
I couldn't find any browsers that do that, sorry. Still, it's certainly possible that they exist, but in that case Firetext already doesn't work in them. Anyway, it's not at all important to do anything, the only reason I mention it is because less overhead is always nice.

**Comment by ferndot** [comment]
@twiss: definitely. I will test this on a device (that may be the environment that @jackd1 is referring to).

**Comment by ferndot** [comment]
@twiss I created a pull request with your suggestion (#250), and tested it on Firefox and a Firefox OS device. There were no problems.
