### ISSUE TITLE
Autozen on the desktop

### ISSUE THREAD

**Issue by twiss** [codexa/firetext#199]
IMHO on the desktop it doesn't make sense to, by default, go into fullscreen when the user opens a document.

So my proposal would be to make the autozen setting a select, with values (true, always, false) and names (Auto, Always, Never). true (which is what most people will have selected now, which will be called Auto) will mean true on mobile, false on desktop.

Another option would be to leave the setting as it is, and just disable autozen on the desktop (i.e., act as if the setting was always set to false.)

Another option would be to trade backward sanity for forward sanity and name the select options (auto, true, false).

**Comment by ferndot** [comment]
On Firetext's first run, settings are set to default values (https://github.com/codexa/firetext/blob/develop/scripts/settings.js#L65-L67). What if we retained the current switch, and just initially set autozen to `true` on mobile and `false` on desktop?

Also, what do you think of using the collapsed zen interface on desktop, but not going full-screen? In my opinion, the desktop implementation of the full-screen API is a bit clunky.

**Comment by twiss** [comment]
> What if we retained the current switch, and just initially set autozen to true on mobile and false on desktop?

Right, I was working on the assumption that settings would get synced between mobile and desktop one day. But I guess today that isn't a problem.

> Also, what do you think of using the collapsed zen interface on desktop, but not going full-screen? In my opinion, the desktop implementation of the full-screen API is a bit clunky.

I think the difference between the two UIs without fullscreen is trivial enough that you should remove the choice between them. And my guess is a handful of people would like the fullscreen mode (writers?). Whether you want to have a header button and a confusing setting for those people is up to you, of course.
