### ISSUE TITLE
Add save ability

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#2]
A text editor needs to be able to save its files!

**Comment by HR** [comment]
Maybe this will help add, modify and delete files:
https://developer.mozilla.org/en-US/docs/WebAPI/Device_Storage?redirectlocale=en-US&redirectslug=WebAPI%2FDevice_Storage_API

**Comment by ferndot** [comment]
Yes^^  I am working on it offline right now.

**Comment by HR** [comment]
Do we need the saving action in the permission section in manifest file (to access api) i.e. 
"permissions": {
  "storage": {
    "description": "Required for writing, reading and modifying files",
    "access": "readcreate", "readwrite"
    }

**Comment by ferndot** [comment]
Looks like we need a `"device-storage:sdcard":{ "access": "readwrite" }` permission.  See: https://developer.mozilla.org/en-US/docs/Apps/App_permissions.

Landed in https://github.com/Joshua-S/FireText/commit/7bfc8d3df7c3a578772c809dce6764d7c22be519.

**Comment by ferndot** [comment]
https://github.com/Joshua-S/FireText/commit/bed2de23a2412e17716cfb849fcbe4a712c93a6a Added save support, but the permissions system is still blocking it.  Any ideas?  (to test go into edit mode, and hit the save button).

**Comment by logan-r** [comment]
Hmmm... It works for me the first time I try to save a file of a certain file name, but after that I get a `NoModificationAllowedError`. Maybe the file is being saved as read-only?

**Comment by ferndot** [comment]
I think that might be it, but I don't know how to get around that 
issue.  The permission says read+write access.  Will ask on IRC tomorrow.

**Comment by logan-r** [comment]
Fixed it!

**Comment by HR** [comment]
how?

**Comment by logan-r** [comment]
If the code can't save the file (because another file of that name exists), it deletes the old copy and then saves the file.

**Comment by ferndot** [comment]
:+1:
