### ISSUE TITLE
[desktop] Printing documents

### ISSUE THREAD

**Issue by twiss** [codexa/firetext#206]
Currently, you can print a document by selecting everything (ctrl-a) first. It would be nice if printing worked without doing that.

**Comment by ferndot** [comment]
This is an important feature for desktop. 

There are several ways to address this issue:
- We could use https://developer.mozilla.org/docs/Web/API/window.print to trigger the print dialog on the iframe with the document's contents. The only caveat is that most browsers print meta information in the header of the document.
- We could cause the browser to download a pdf version of the file (after we implement pdf support). This is what Google Docs does.

Any other ideas?

**Comment by twiss** [comment]
Another idea is to try and use `media=print`/`@media print` to hide everything but the document. One problem with that is that it doesn't print the whole document, just the part that's visible. So you'd have to make all of it visible first.

**Comment by twiss** [comment]
Calling `window.print()` from within the iframe in Chrome works fine, including metadata from the top iframe. In Firefox Nightly on linux it doesn't work in at least some cases, I'll see if I can file a bug with them.

**Comment by ferndot** [comment]
In that case, this feature should be simple to solve. I think that we should wait to fix this until there is a plan in #203. What do you think?

**Comment by twiss** [comment]
I've filed a bug in Firefox with details: https://bugzil.la/1095808

Only downside of `print()` versus `@media print` is that with the latter, selecting print from the browser menu also works. I guess though that a print button inside Firetext is more like what people expect. Also, we could intercept `ctrl-p`.

**Comment by ferndot** [comment]
> I've filed a bug in Firefox with details: https://bugzil.la/1095808

Thanks! It is definitely a Firefox on Linux issue because it works fine on OS X.

> I guess though that a print button inside Firetext is more like what people expect.

I would expect that as well. The print menu item connotes printing the entire page, not just the document. Also, keyboard shortcut interception will be a good feature in the future!

**Comment by Ryuno-Ki** [comment]
> Also, keyboard shortcut interception will be a good feature in the future!

When intercepting keys, please, bear in mind, that screenreader users depend heavily on them.

**Comment by twiss** [comment]
> When intercepting keys, please, bear in mind, that screenreader users depend heavily on them.

Good point, I'll file some issues about that. Is `ctrl-p` something important in screenreaders (or elsewhere for that matter)?

**Comment by Ryuno-Ki** [comment]
Umm, I assume not so. Orca didn't get it to upload their default keystrokes, so I have to dig into the code in order to extract them.

Meanwhile, I can point you to
- [keystrokes for JAWS](http://doccenter.freedomscientific.com/doccenter/archives/training/jawskeystrokes.htm)
- [keystrokes for NVDA](http://accessibility.psu.edu/nvda)
- [kesstrokes for VoiceOver](http://www.applevis.com/guides/voiceover-keyboard-shortcuts-mac-os-x)

Shall I copy-paste those links into one of the other issues?

**Comment by twiss** [comment]
Thanks a lot for those links! Just here is fine, I'll refer to them there.

**Comment by Ryuno-Ki** [comment]
I discovered Orca being hosted on GitHub as well.

At first glance, I'd say, these files look promising:
- [keynames](/GNOME/orca/blob/master/src/orca/keynames.py)
- [laptop_keyboardmap](/GNOME/orca/blob/master/src/orca/laptop_keyboardmap.py)
- [desktop_keyboardmap](/GNOME/orca/blob/master/src/orca/desktop_keyboardmap.py)
- [common_keyboardmap](/GNOME/orca/blob/master/src/orca/common_keyboardmap.py)

Of course, all of them can be customised to one's pleasure, but we're just dealing with the default ones.

I'll look after spare some time to wrap the files into a table for easier consuming.

**Comment by twiss** [comment]
Another option is to `window.open()` the document.

Depending on how we implement that, that would allow the user to access their browser's print preview and page setup features (Firefox and IE, unlike Chrome have these separately from their `window.print()` popup).

The question then is whether we want that. Allowing access to page setup would make the most sense if the changes made there would have effect in the editor, and thus we didn't have our own dialog (#239).

**Comment by ferndot** [comment]
Fixed by #252
