### ISSUE TITLE
[desktop] Chrome-style menu

### ISSUE THREAD

**Issue by twiss** [codexa/firetext#207]
Maybe it makes more sense to make the menu some sort of dropdown instead of a sidebar on the desktop?

**Comment by ferndot** [comment]
That does sound good. The menu is much less overpowering than a sidebar.

**Comment by twiss** [comment]
Re #222,

> This is a good start. It does need some UX polish, but that can be done after the merge =)

Sure. It's mostly a matter of taste, but something like this maybe:
- [ ] Reduce contrast (i.e. don't make it so dark)
- [ ] Remove the bar with "Menu" since it's kinda obvious
- [ ] A little arrow to the button, as e.g. Firefox has
- [ ] Some padding and border-radius
- [ ] Also, I tried to give it a max-height and keep the scrollbar intact, but couldn't get it to work

**Comment by ferndot** [comment]
@twiss :+1: for those ideas!

**Comment by ferndot** [comment]
Reopening to track refinements.

**Comment by ferndot** [comment]
How is this?

![screen shot 2014-11-27 at 3 24 28 pm](https://cloud.githubusercontent.com/assets/1479244/5221828/759b4a62-767c-11e4-80c4-2a3d1fb08d6b.png)

**Comment by twiss** [comment]
Looks great! (My only nitpick would be the border, although I wouldn't know better offhand -- maybe a border on all sides? Still much better than it is now though, feel free to just merge that)

**Comment by ferndot** [comment]
@twiss, so you would rather it be a sort of "bubble menu?" Similar to the Firefox hamburger menu?

**Comment by twiss** [comment]
That's what I had in mind originally, yes. Not that it looks bad like it is, though.
