### ISSUE TITLE
Firetext vector logo

### ISSUE THREAD

**Issue by HR** [codexa/firetext#21]
Does anyone have the Firetext logo in vector format?

**Comment by ferndot** [comment]
We probably should re-design the logo.  https://www.dropbox.com/sh/sftlo2pefxuc7ai/jMqlxVJzIA/new_logo.png is something I've done.  Is it good enough?  Or do you guys have something better.

**Comment by HR** [comment]
I'm a graphic designer and logo designer. I've vectorised in more format (e.g. .pdf, .ai,..) https://www.dropbox.com/s/9m5p6ikj3ef4hoq/Firetext_icon.zip
But I''ll improve the design for you, to make it great!
My eportfolio: http://www.behance.net/theARTstudioss (worked for theartstudioss)

**Comment by ferndot** [comment]
Wow, thanks!

Do you need the xcf?

**Comment by HR** [comment]
Not really supported by many, you're welcome.
