### ISSUE TITLE
[desktop] Firefox doesn't support editing keyboard shortcuts

### ISSUE THREAD

**Issue by twiss** [codexa/firetext#211]
`ctrl-b`, `ctrl-i`, `ctrl-u`.

They all have a meaning: show bookmarks, show page info, show page source.

Personally I wouldn't think it a problem to override those in an editor, but maybe Firefox thought differently. Maybe we should file an issue with them.

Also, they might mean still different things elsewhere (as mentioned in https://github.com/codexa/firetext/issues/206#issuecomment-62367711)

**Comment by twiss** [comment]
Screenreader default shortcuts: https://github.com/codexa/firetext/issues/206#issuecomment-62423070

Apart from the bindings I mentioned above, there's `ctrl-i` = Open favorites in JAWS.

IMO none of these bindings are very important, especially if they work after leaving editor's focus (#212). Still, it's strange that Firefox hasn't implemented them.

**Comment by jackd1** [comment]
Those are all pretty standard word processor shortcuts, users will probably expect them to do that.
