### ISSUE TITLE
[desktop] Downloading documents

### ISSUE THREAD

**Issue by twiss** [codexa/firetext#217]
Similarly to uploading (#216).

The straightforward fix would be to offer downloading files in the format they're in, in addition to "print to pdf" which browsers offer (#206).

Additionally, we could offer some conversions. If we switch to WebODF (#189) as the default editor, Microsoft Word supports that too so converting isn't too important, I think. If we don't, (or maybe anyway) we should offer html -> odt/docx conversion.

**Comment by ferndot** [comment]
> we should offer html -> odt/docx conversion.

The difficulty is that there are practically no usable client-side parsers for these formats. That is why we don't have support for them yet.

**Comment by twiss** [comment]
That's unfortunate. For this particular issue we "need" to create them though, not parse them.

**Comment by jackd1** [comment]
Converting one way, from html to odt/docx is significantly simpler than parsing odt/docx to be edited, but it will still take a bit of time to implement.

**Comment by twiss** [comment]
Fixed by #277.
