### ISSUE TITLE
Official website

### ISSUE THREAD

**Issue by HR** [codexa/firetext#22]
I need access to the official website for the app for google api setup and other stuff

**Comment by ferndot** [comment]
Caught me unprepared for that one :(

I don't actually have a website for FireText yet.  I did, but that was when I was developing it alone.  Here is the old page: http://micovision.bugs3.com/FireText/.

**Comment by HR** [comment]
I would recommend ipage as web hosting, is the cheapest and you get a lot of extras and GET a FREE DOMAIN (100$ Google advertising, cms, sitelock and more). 

<h3><a href="http://www.ipage.com/join/index.bml?AffID=717459">iPage</a></h3>

**Comment by ferndot** [comment]
What should the site be called?

Firetext.com/org is already taken, and if we want to create more projects, we should have a different name anyway.

**Comment by HR** [comment]
a company maybe?

**Comment by ferndot** [comment]
Yes, or at least an organization name.

When we do that, I will transfer the FireText app over to the org's github :)

**Comment by HR** [comment]
what about something like "Codex"

**Comment by ferndot** [comment]
That sounds cool, but...that's already been taken (actually by a group on Codecademy)

**Comment by HR** [comment]
codexa.org

**Comment by HR** [comment]
what dou you think?

**Comment by ferndot** [comment]
Let's ask @Logi0.
