### ISSUE TITLE
navBack() Function Breaks

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#23]
Steps to reproduce:
- Open a file.
- Click the menu.
- Click "Open a file..."
- On the dialog, click the back button.
- Go to the menu again and click "Create a new file."
- Click the back button.

Result:
document.getElementById is null.

This is probably a result of my dumb implementation...

**Comment by HR** [comment]
Ya, this is one of the first thing I noticed and this still causes error in the drawer if you want to add a go back button

**Comment by ferndot** [comment]
There is already a go back button I thought...

I wish there was a regions script included in the building blocks...

**Comment by ferndot** [comment]
Fixed!
