### ISSUE TITLE
Toolbar gets hidden on mouseenter in Firefox desktop

### ISSUE THREAD

**Issue by twiss** [codexa/firetext#231]
As per your suggestion, split out of #195 since that morphed into a more general toolbar on the desktop bug.

> In Firefox desktop, when moving the mouse out of the editor and in again (which happens easily because the toolbar button is close to the edge), the editor gets focused (https://github.com/codexa/firetext/blob/0f43b6a6/scripts/firetext.js#L124 since 26f97ba) which causes the toolbar to hide, which is a bit annoying.

Also, if possible it would be nice to solve this issue independently of #195, since the same problem happens when testing the mobile layout on a desktop.

**Comment by ferndot** [comment]
Is this an issue with #274? I cannot reproduce!

**Comment by twiss** [comment]
Can't reproduce either; the toolbar never gets hidden on desktop.
