### ISSUE TITLE
Autozen mode doesn't work on android

### ISSUE THREAD

**Issue by twiss** [codexa/firetext#232]
This is not as simple as it looks, since we also sometimes open a document on startup without any user interaction (hence we can't enter fullscreen mode).

**Comment by jackd1** [comment]
Maybe if they are in autozen and a document opens on start up, make a popup to ask if they want to go in zen mode, then fire full screen after they hit ok.

**Comment by ferndot** [comment]
This will be fixed by removing autozen in #274.

**Comment by ferndot** [comment]
Fixed!
