### ISSUE TITLE
[proposal] Only use zen mode

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#234]
What if we removed support for the "normal" editing interface, and only used the zen mode interface (regardless of whether the app is in full-screen). I have already turned the default interface off by default, and IMO it uses too much screen space.

What are your thoughts?

**Comment by twiss** [comment]
Well, non-zen mode shows the name of the document, and I would like to have renaming by clicking on that at some point.

What you could do is:
- On mobile, switch to zen mode whenever the editor is focused (i.e. when the keyboard is up). Remove the zen mode button.
- On desktop, leave it like it is, or remove the zen mode button (and thus the mode) there.
- Remove the autozen setting.

**Comment by ferndot** [comment]
What if we just had a "Rename document" item in the sidebar on mobile. And, included the filename at the top of the sidebar (E.g. "Editing foo.html")?

**Comment by twiss** [comment]
Sure, and/or in the `<title>`, and/or you could just use the layout you proposed in #203 and show the first few letters of the title with an ellipsis.

**Comment by ferndot** [comment]
This is the mobile UI changed by the new tab style in #258.

![screen shot 2014-12-01 at 03 03 17](https://cloud.githubusercontent.com/assets/1479244/5426249/c772c194-833d-11e4-83e3-22fd1fe50e04.png)

**Comment by Ryuno-Ki** [comment]
Hm, WordPress has kind of Zen mode, too.
Here, the header and footer would disappear and only fade in, if the user scrolls.

**Comment by ferndot** [comment]
@Ryuno-Ki because of the mobile screen constraints, do you believe that it would be beneficial to have that in "normal mode?" E.g. #260

**Comment by Ryuno-Ki** [comment]
Dunno.

For me, I prefer writing/editing on a desktop. At least for the header I can imagine it may be beneficial (after optimising the transition speed and durance).

The footer should be more context sensitive, imho. That is, if I can mark (can I? Firefox OS didn't rolled that out, yet) text, then I may want to format it. Before that, I see no need in it.

**Comment by ferndot** [comment]
@Ryuno-Ki that is a wonderful suggestion for the footer. The newer versions of Firefox OS now have text selection capabilities, and we could disable the feature on older versions.

**Comment by Ryuno-Ki** [comment]
Glad to help :)

**Comment by ferndot** [comment]
Fixed by #274
