### ISSUE TITLE
Google api required info

### ISSUE THREAD

**Issue by HR** [codexa/firetext#24]
Hey,
I need some info for creating google api(for application):

Open URL (Required) 

> This URL is used when the user opens an existing Google Drive item with your application.

New URL (Required) 

> This URL is used when the user selects your application from the "New" menu in Google Drive.

**Comment by ferndot** [comment]
Hmm, looks like Google Drive only works with websites.  Is that true?

I have been thinking that we should make a desktop version, but we need to finish the app too...

**Comment by HR** [comment]
I need it for Google Drive SDK

**Comment by ferndot** [comment]
Wait, does it have to be an existing url?  Or is it just a google url?

**Comment by HR** [comment]
ya, for this I need website
read: https://developers.google.com/drive/enable-sdk#open_url
read(new url): https://developers.google.com/drive/integrate-create

**Comment by ferndot** [comment]
Can you change the website multiple times?

**Comment by HR** [comment]
yes, probably... but we are just about to get a website, right?

**Comment by ferndot** [comment]
I am not able to buy the domain right now, so we will have to use a free subdomain temporarily.  Also, we don't really _have_ a site yet...

Sorry :(

**Comment by HR** [comment]
ok, no prob

**Comment by logan-r** [comment]
Maybe for version 0.2?

**Comment by ferndot** [comment]
Sure :)

**Comment by HR** [comment]
ya, but quick to stay competitive(api implementation on new os)

**Comment by HR** [comment]
So with the domain set up, how can we add a open URL(host the application?)

**Comment by ferndot** [comment]
Well, this app doesn't work on desktop currently, but we can start work on a desktop version if you want...  Just create a desktop_0.1 branch.
