### ISSUE TITLE
Generate complete html files

### ISSUE THREAD

**Issue by twiss** [codexa/firetext#245]
Including `<html><body>` boilerplate. Currently we generate html fragments.

That's after all what an `.html` file is. Also, we then have a logical place to put (if we want) the document's language, direction, charset, styles, page settings (#239), metadata, etc.

The logical way would be to put the document alone in an iframe (as opposed to in a `<div>`), but then we have to figure out where to put our editor's scripts and styles.

**Comment by ferndot** [comment]
:+1:!

I think that we should generate a complete html file on document creation, and leave opened files as-is. What do you think?

What about this strategy:
- Load document `<body>` into editor `<div>`
- Append any `<style>`s to editor `<body>`
- Parse additional `<head>` tags

**Comment by Ryuno-Ki** [comment]
I wonder, how CodePen.io handle this …

**Comment by ferndot** [comment]
CodePen packages the HTML inside the `<body>` of a template. I don't think that we want to do that.

**Comment by ferndot** [comment]
Fixed by #246!
