### ISSUE TITLE
Description inconsistent between marketplace and transifex

### ISSUE THREAD

**Issue by yfdyh000** [codexa/firetext#248]
https://www.transifex.com/projects/p/firetext/viewstrings/#en/marketplace/22957353
_Error Reporting and Feedback: Please report issues, give feedback and make feature requests by emailing us at support@codexa.org. Thank you!_

https://marketplace.firefox.com/app/firetext?lang=en
_Error Reporting and Feedback: Please report issues, give feedback and make feature requests by emailing our support email. Thank you!_

This has led to a little incorrect translations.

**Comment by ferndot** [comment]
Thank you for noticing this, @yfdyh000!

The support@codexa.org email is no longer active, so I changed the description on the Marketplace to be more generic (and point to our new support email). I must not have updated Transifex.

Fixing this with #249

**Comment by ferndot** [comment]
I fixed this on Transifex!
