### ISSUE TITLE
"This app requires an SD card"?

### ISSUE THREAD

**Issue by yfdyh000** [codexa/firetext#249]
https://www.transifex.com/projects/p/firetext/viewstrings/#en/marketplace/22957361
_Requirements: This app requires an SD card, and permission to access it. Also, the USB Mass Storage preference must be turned off, or there will be an error._

This needs to be clarified, I don't have a SD card and use properly, it should be able to run properly on a internal storage.

**Comment by ferndot** [comment]
@yfdyh000 what about: "This app requires available storage space, and permission to access it. ..."?

Although, even that may not apply anymore. Firetext might function well without either an internal storage or sdcard. I will test it presently.

**Comment by yfdyh000** [comment]
Looks good.

It maybe able to works in memory only, but if the description said need storage space is also correct, because memory only is a special case.

**Comment by ferndot** [comment]
Fixed on Transifex!
