### ISSUE TITLE
Improve no storage message

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#251]
When no available storage methods exist, we display an error banner. Instead, we could display a positive "Set up a storage system" message and button. The button would call `regions.nav('settings')`.

This would make it simpler for a new user to set up a storage.

**Comment by safwanrahman** [comment]
Can you please provide the Steps to Reproduce? @joshua-s

**Comment by ferndot** [comment]
1) Load Firetext in Firefox Nightly (https://github.com/codexa/firetext/wiki/Get-Coding#using-firefox-nightly)
2) Click the pen icon
3) There is a red, "no-storage-available" banner. (created by https://github.com/codexa/firetext/blob/develop/scripts/firetext.js#L260)

**Comment by ferndot** [comment]
@safwanrahman any luck reproducing this?
