### ISSUE TITLE
[desktop] Declare media queries inside <link> tag

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#254]
It might be beneficial to include the desktop media query inside [the `<link>`](https://github.com/codexa/firetext/blob/b01ad2e93bfa4588983bb3e665ece89b3e4b8bd7/index.html#L78) instead of [its current location](https://github.com/codexa/firetext/blob/b01ad2e93bfa4588983bb3e665ece89b3e4b8bd7/style/desktop.css#L1).

It will make indentation less of a bother. I don't know if it has any current performance benefits, but [it may in the future](https://scottjehl.github.io/CSS-Download-Tests/).

**Comment by abhishekvp** [comment]
Submitted a pull request for this issue: https://github.com/codexa/firetext/pull/266
