### ISSUE TITLE
[desktop] UI

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#258]
(Split from #203)

Implement a usable and visually attractive interface for large devices.

Code is located in the [desktop-design](https://github.com/codexa/firetext/tree/desktop-design) branch. Feel free to assist!

**Comment by ferndot** [comment]
@twiss: are the margin indicators required for the desktop design?

![screen shot 2014-12-12 at 3 08 04 pm](https://cloud.githubusercontent.com/assets/1479244/5418507/ae8906a6-823a-11e4-930d-2392a3e01fef.png)

**Comment by twiss** [comment]
Yeah, because at some point we should increase the padding to match what comes out of a printer.

**Comment by ferndot** [comment]
Ah, that makes sense.

**Comment by Ryuno-Ki** [comment]
Isn't that printer dependent?

I remember having to fiddle around with LaTeX back then, to get the business cards look like I wanted them to (that is, match the cutting lines of that special paper …).

**Comment by twiss** [comment]
It is, but you can give some hints to the browser about preferred page size and margins ([@page](https://developer.mozilla.org/docs/Web/CSS/@page), probably doesn't work perfectly though), which we then have to infer from the locale (#239). Another more reliable way would be to download a pdf (as per #206), then you have to select print twice though.

**Comment by ferndot** [comment]
The second approach is what Google Docs does for Firefox.
