### ISSUE TITLE
New program flow

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#26]
With the implementation of the sidebar, the welcome screen is not needed anymore, and is rather unintuitive.

I think that we should open the edit region on program startup and load the last opened file.  If there is none, we should show the document browser (#25).

What are your thoughts?

**Comment by HR** [comment]
Yup, that would be good but we still need a file explorer(with folders) to organise and browse work

**Comment by HR** [comment]
sorry, accidently closed

**Comment by logan-r** [comment]
Oops... after seeing this my last commit probably should be reversed.

**Comment by ferndot** [comment]
Can you do that please.

A formatting sidebar would be nice, but it should be a different sidebar :)

**Comment by logan-r** [comment]
I kind of prefer the original layout (with welcome screen, etc.) and using the sidebar for formatting. I think this is a lot more intuitive, but that is just my option.

**Comment by HR** [comment]
The welcome screen should have an file explorer, but the sidebar is the next big thing.

**Comment by ferndot** [comment]
Ok, so I should stick with current flow?

**Comment by logan-r** [comment]
I think so, should I un-reverse my sidebar update commit?

**Comment by ferndot** [comment]
I don't know, the toolbar is for formatting...I guess you can do whatever you think is best.

**Comment by ferndot** [comment]
@Logi0 can we do the formatting dialog instead, now that I've been looking, it seems more logical to use the sidebar for the previous things?

Sorry for the confusion...

**Comment by logan-r** [comment]
OK, I'll just un-un-reverse my sidebar commit... :D
Can we not get rid of the back arrow, though?

**Comment by ferndot** [comment]
That can stay, I'll figure out a different way to launch the sidebar :)
