### ISSUE TITLE
Rich text in night mode

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#267]
Currently, we change the colors of rich text documents in night mode. Unfortunately, that destroys WYSIWYG. What should we do to rich text files in night mode?

A few possible approaches:
- Change document background and text colors (current functionality)
- Keep the document as it is (e.g. white background and black text by default)
- Invert the document (using CSS filters)

**Comment by twiss** [comment]
I think it depends a little bit on what you're doing: (in order of likeliness to want night mode) reading, writing, or laying out a document.

> - Invert the document (using CSS filters)

That sounds like an improvement to what we currently have in some cases (e.g., when the document explicitly sets `color: black` for some text) but we probably shouldn't invert anything which has a color (link text, images). Another option is to convert (possibly only the text) to grayscale and then invert.
