### ISSUE TITLE
Recent Docs List

### ISSUE THREAD

**Issue by logan-r** [codexa/firetext#27]
We need a way to store the recent docs.

**Comment by ferndot** [comment]
@Logi0 are we still planning to do the recent docs list?  I was envisioning a list of all docs on the welcome screen (although they could be sorted by edit date).

**Comment by HR** [comment]
Please add a File explorer

**Comment by ferndot** [comment]
see #25!

**Comment by logan-r** [comment]
@Joshua-S I think that the docs list should only show files that the user has created or opened. The open dialog should list all the docs. But if you or @HRanDEV wanted to list all the docs we could do that instead.

**Comment by ferndot** [comment]
The only problem that I have with the open window is that it is just a dialog, and not for creating/renaming/deleting files.

Is this a good compromise: have recent docs on top, and then a field that shows all docs below?

**Comment by logan-r** [comment]
I think that would work!
Could the all documents field be expandable, so the user doesn't get overwhelmed with documents?

**Comment by ferndot** [comment]
If you look at the latest, I now have an edit mode button (it doesn't work yet, but it is there!).  This will allow you to rename/delete files.  Also, you can only open from the open dialog (you shouldn't be able to add).

**Comment by ferndot** [comment]
Also, when we add cloud storage, we can add sections for them.

**Comment by HR** [comment]
I don't think we should exclude the sidebar because it makes it very excessive for the user to open files via api, create file, browser files(add a dialog wouldn't overwhelm user) and do loads of more... So it should be there in the edit section and even in main(for api file loading)

**Comment by ferndot** [comment]
We fixed it!

**Comment by logan-r** [comment]
I think this is done!
