### ISSUE TITLE
Logo drafts

### ISSUE THREAD

**Issue by HR** [codexa/firetext#28]
So I designed some drafts for the firetext logo(s). What do you guys think and which one is the best?(two logos/images needed: one for the application and one for documents)
https://www.dropbox.com/s/nbty6n6rf3iinq7/firetexticdrafts.zip

**Comment by ferndot** [comment]
Oooh, I like!  Maybe firetext4 for the logo, firetextic.png for FireText documents, and modifications of firetextic2 to show the different formats.

**Comment by HR** [comment]
Thanks took a bit time to make logo, what do you think @Logi0?

**Comment by ferndot** [comment]
Also, we have a new team member!  Welcome to FireText @Graeme22 :)

@Logi0, I think you know each other from @HTML5-Games.

**Comment by logan-r** [comment]
@HRanDEV AWESOME! :D 
I think `firetextic` is the best.

**Comment by HR** [comment]
Ok we'll choose `firetextic4` as the logo and `firetextic` as file extension icon(.txt,.html, .rtf, .odml, .doc, .docx,....)

**Comment by ferndot** [comment]
Perfect!
