### ISSUE TITLE
Docs List

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#3]
A docs list is necessary to be able to open files as Firefox OS has no native browser for files stored on an sd card.

See:
https://github.com/Joshua-S/FireText/tree/master/style/bb/edit_mode
https://github.com/Joshua-S/FireText/tree/master/style/bb/lists

Also see:
https://github.com/mozilla-b2g/gaia/tree/v1.0.1/apps/sms
https://github.com/mozilla-b2g/gaia/tree/v1.0.1/apps/email

**Comment by ferndot** [comment]
Does anyone want to take this?  If not, I can do it.

**Comment by HR** [comment]
what do u mean with docs list?

**Comment by ferndot** [comment]
Something like this mockup: https://www.dropbox.com/s/0hyq9sdx6lad0ib/list.png.

**Comment by ferndot** [comment]
@Logi0 started a list with this commit: https://github.com/Joshua-S/FireText/commit/4a10b798c8d557d157a705d6ad796f324a02b7a1.

**Comment by ferndot** [comment]
@Logi0 I am starting to think that you should be the leader of this project :D

**Comment by ferndot** [comment]
Looks fixed!
