### ISSUE TITLE
Implement Edit Mode

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#30]
Edit mode will be a very handy tool.  It will allow the user to rename and delete files from their documents folder.

Edit mode will be located on the welcome region, and is activated by, you guessed it, the edit mode icon!

**Comment by ferndot** [comment]
Added the core functions in https://github.com/Joshua-S/FireText/commit/f4557336851d6207ec4fc32bf48cefcf65730dac.

**Comment by ferndot** [comment]
Ugh, this one is tricky!

@Logi0 could you please give me some help with the buildEditDocList function?

**Comment by logan-r** [comment]
Sure!

**Comment by ferndot** [comment]
I think there was a regression.

**Comment by ferndot** [comment]
Fixed it!  Can we focus on this today?

**Comment by logan-r** [comment]
Yep, I can help right after I fix #46.

**Comment by ferndot** [comment]
Should we move this to v.0.2, or should I extend the due date for v.0.1?

**Comment by logan-r** [comment]
Maybe you should extend the due date by 3 days.

**Comment by ferndot** [comment]
Done!

**Comment by logan-r** [comment]
Just add "delete selected" functionality. I'm not sure how to implement "rename", though. Will it rename all selected files or just one? Is this feature required for version 0.1?

**Comment by ferndot** [comment]
It will show text boxes in place of the filename.  No, I think delete will be good enough for 0.1 :)

Thanks for doing this, I couldn't figure out how to do it.

**Comment by HR** [comment]
I think that we should get rid of the "Editing..." word in the title, what do you think?

**Comment by ferndot** [comment]
I'm fine with it.  @Logi0?

**Comment by logan-r** [comment]
Yeah, that should be fine.

**Comment by logan-r** [comment]
I think this is done (at least for version 0.1)!

**Comment by ferndot** [comment]
great!
