### ISSUE TITLE
Firetext website

### ISSUE THREAD

**Issue by HR** [codexa/firetext#31]
Here is a subdomain I created (has wp installed), that we can use as our temporary website:
http://firetext.co.nf/

**Comment by ferndot** [comment]
Great @HRanDEV!  I'll create a website branch or repo for it soon.

**Comment by HR** [comment]
or just use a wp template(we have root access)

**Comment by ferndot** [comment]
Email me the login info please :)

**Comment by logan-r** [comment]
Me too!

**Comment by HR** [comment]
I'll create users for you

**Comment by HR** [comment]
I've sent you the info(you both have unique password)

**Comment by ferndot** [comment]
I didn't get it :(

**Comment by logan-r** [comment]
Me neither :cry:

**Comment by HR** [comment]
ok, I send you them manually then

**Comment by HR** [comment]
I sent them and NOTE the \* are just for SECURITY(email> to protect user+pass) and THE \* ARE NOT PART OF USERNAME/PASSWORD

**Comment by HR** [comment]
have you received them?

**Comment by logan-r** [comment]
Yep! Where do I log in, though?

**Comment by HR** [comment]
http://firetext.co.nf/wp-login.php

**Comment by logan-r** [comment]
@HRanDEV Thanks!
