### ISSUE TITLE
Unique word processor

### ISSUE THREAD

**Issue by HR** [codexa/firetext#33]
We need Firetext to be unique and stand out from all the other ordinary/boring text edit apps, so share your ideas! 
Well, I have a great idea: what if the more than 1 person could collaborate on one text file? And comment on changes as well as have a history of changes. These changes logs could be stored in local in .txt

It is a bit like github but mobile, compact and instant for text. This could be really useful for example if someone is writing a book and wants his friend to collaborate and help, so then this would be great.

Also we need more word processing we need table, font, picture, +more and for coding we need syntax highlighting for .html.

**Comment by logan-r** [comment]
As far as I know, there isn't a full functioning word possessor for Firefox OS yet (besides a few note apps).
I like the multiple people editing idea. (Maybe version 0.3? We would need the files to be stored on the cloud.)

**Comment by ferndot** [comment]
Sounds awesome, and no, there isn't even a beta word processor yet!﻿

**Comment by HR** [comment]
Ya, and how long do you think it is going to take for a "beta" word processor to exist. In fact it not not hard at all because unlike android which is build on java, firefox os is built on html5 and javascript and for sure there are html5 web editors out there that are way better. So how long is it going to take for someone to make an app for firefox os? Not very long...
That is why we need to be ahead of ordinary processors/editors to stay competitive we have to offer a unique feature that makes us stand out!

**Comment by Graeme22** [comment]
I agree. also personally I don’t really care what color the header is. but the working w/ other people online is a great idea.

**Comment by ferndot** [comment]
Yes, that is going to be huge if we can pull it off!

**Comment by Graeme22** [comment]
yup

**Comment by ferndot** [comment]
Created #35 to track that feature, and the band-server repository for server-side work.
