### ISSUE TITLE
Firetext 0.5.1 broken in simulator

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#350]
From @Ryuno-Ki:

> For whatever reason I cannot launch Firetext v0.5.1 in Simulator (Timeout).
> 
> When I wait a bit longer, I can see the app, but cannot interact with files:
> 
> ```
> NS_ERROR_FILE_NOT_FOUND:  modules.js:74:0
> logged 1 error to Bugsense, status: {"data": {"eid": 4852208084, "handled": 0}, "error": null}
> ```

We need to investigate and fix this issue.

**Comment by Ryuno-Ki** [comment]
I used Firefox OS v1.3 as OS to simulate.

**Comment by ferndot** [comment]
@Ryuno-Ki do you remember if all your submodules were up to date?

**Comment by Ryuno-Ki** [comment]
I don't. How can I check? I didn't touched anything related since then.

**Comment by ferndot** [comment]
I'd suggest pulling from `develop` and then running `git submodule update --init --recursive`. Then, you could check if Firetext still fails to run in the simulator.

It would also help to know which module `modules.js` was loading. You can retrieve that info easily by finding the last "Loading ..." message in the console.

**Comment by Ryuno-Ki** [comment]
The simulator complains:

> app submission to the Marketplace requires a 128px icon

Opening a blank test.txt yields this in the browser console:

```
not well-formed [index.html:20:73]
syntax error [dropbox.min.js:1:1]
not well-formed [dropbox_authdriver_firefoxos.js:1:1]
not well-formed [cloud.js:1:1]
not well-formed [cloud_dropbox.js:1:1]
not well-formed [es6-promise.min.js:1:1]
not well-formed [FileSaver.js:1:1]
not well-formed [gesture_detector.js:1:1]
not well-formed [stringview.js:1:13]
syntax error [bugsense.min.js:1:1]
not well-formed [modules.js:1:1]
NS_ERROR_FILE_NOT_FOUND:  [modules.js:74:0]
logged 1 error to Bugsense, status: {"data": {"eid": 4852208084, "handled": 0}, "error": null} [bugsense.min.js:2]
```

So, yes, still the same error in Simulator. Is it possible to persistent files there? I mean, without a "flash memory" …

It loads way faster!

**Comment by ferndot** [comment]
Which simulator version are you using? I could not reproduce on 2.2.

> Is it possible to persistent files there? I mean, without a "flash memory" …

I believe that the newer simulators persist files by saving them to folders in their profile directories.

**Comment by Ryuno-Ki** [comment]
1.3 - in order to prove the behaviour described above (I assume, many early adopters will got stuck on v1.3. For example, have there been updates to Alcatel OneTouch Fires?).

I don't find an installed Firetext on v2.2 - the Rocket Launcher ("I'm looking for") suggests to _install_ Firetext (which doesn't have any effect either).

**Comment by ferndot** [comment]
@Ryuno-Ki I am not able to reproduce either by pushing Firetext to the 1.3 simulator or by installing it from the marketplace. I suspect your installation of either Firetext or the simulator might be corrupted.

If you would like to try a re-installation, be my guest. If that is not the problem, I'd be interested to investigate further. Otherwise, this issue can be marked as WONTFIX since Firefox OS is ending support soon.

**Comment by Ryuno-Ki** [comment]
Mark it as WONTFIX and close the issue, please.
