### ISSUE TITLE
Line breaks in .txt

### ISSUE THREAD

**Issue by logan-r** [codexa/firetext#37]
Line breaks don't work in `.txt` files (the editor uses `<br/>` instead of `\n`).

**Comment by ferndot** [comment]
We will need to fix that.

Please put the code to fix that in resources/txt/parse.js.  Resources is the folder for our parsers.

**Comment by ferndot** [comment]
Was this fixed by your last few commits?

**Comment by logan-r** [comment]
Almost, I just have to get it to save and parse the files as `.txt`.

**Comment by ferndot** [comment]
ok!
