### ISSUE TITLE
New organization!

### ISSUE THREAD

**Issue by HR** [codexa/firetext#38]
I created a organization called "Codexa", what do you think?
https://github.com/Codexa
You are both in.

**Comment by ferndot** [comment]
:+1: I am going to transfer the repo to it!

Thanks!

**Comment by HR** [comment]
You're welcome to do so(its our organisation/company), thanks.

**Comment by ferndot** [comment]
Just did :)

**Comment by HR** [comment]
thanks, now the development is going to be over there.

**Comment by ferndot** [comment]
Can you please make an email for us (preferably admin@firetext.co.nf) and email me the info (so I can make our marketplace account)?

**Comment by HR** [comment]
sure!

**Comment by HR** [comment]
mailed
