### ISSUE TITLE
Welcome to Codexa!

### ISSUE THREAD

**Issue by HR** [codexa/firetext#39]
"Codexa" is our new company/organization from which we are going to create further apps and other products such as firetext. So all the main coding will go on here.
And at later stages, we can register the Codexa.org domain for company recognition.
We as a team are the company and need to collaborate!
<b style="color:red;">Only add experienced and committed coders to the organisation.<b>

**Comment by HR** [comment]
I am going to design company/org logo and other designs, and by the way should codexa be a company or organization?

**Comment by ferndot** [comment]
Well, on Codecademy, people voted for open source.  We could do something similar to what Mozilla does (non-profit with a profit subsidiary).  But lets just have an organization right now.

**Comment by HR** [comment]
<b style="color:red;">Only add experienced and committed coders to the organisation.<b>

**Comment by ferndot** [comment]
That's what I was planning.  Only us and @Graeme22 for right now.  Others can make pulls!

**Comment by HR** [comment]
yes, I totally agree but (Graeme22 should collaborate I think)

**Comment by ferndot** [comment]
What do you mean?

**Comment by HR** [comment]
participate more in discussions (in positive way)

**Comment by Graeme22** [comment]
sorry guys havent been able to help much yet... ive been busy but ill help soon.

**Comment by HR** [comment]
It is ok, looking forward for your help :)

**Comment by ferndot** [comment]
Closing as everyone has seen this.
