### ISSUE TITLE
Drawer not formatted properly

### ISSUE THREAD

**Issue by HR** [codexa/firetext#40]
The drawer isn't formatted correctly and doesn't look like how it should be(https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/UX/Patterns/Drawer)
with the special gray UI, we are also missing the settings icon(very important) and maybe ad button(for opening/new files).

Some helpful links:
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/UX/Patterns/Drawer
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/UX/Patterns/Drawer/Coding
http://buildingfirefoxos.com/building-blocks/drawer/

**Comment by HR** [comment]
Can anyone fix this?

**Comment by logan-r** [comment]
I'll update the header. We don't have a settings dialog yet, though.

**Comment by ferndot** [comment]
Settings are for 0.2 (have to be for DropBox).
