### ISSUE TITLE
Release date and completion

### ISSUE THREAD

**Issue by HR** [codexa/firetext#41]
So by when will all the bugs be resolved and by when can we publish the app?

**Comment by ferndot** [comment]
Well, we have at least one bug to fix before we release 0.1 (I am working on it right now #13).

The first milestone is due in 3 days, we can ship it without edit mode if we need to.

**Comment by HR** [comment]
I have verified the email for you and the pass(same as yours)

**Comment by ferndot** [comment]
Thanks, I am not allowed on gmail.

Could you make a Gravatar for us, and attach it to the GitHub?

**Comment by HR** [comment]
So are we ready yet?

**Comment by logan-r** [comment]
No, but almost. Just #46 left and then we should all test it for a while to make sure there is no bugs left.

**Comment by ferndot** [comment]
Yep, coming down the homestretch for the first milestone!

**Comment by HR** [comment]
There is no settings panel for when you click the setting button, can we make one before release?

**Comment by ferndot** [comment]
I am working on a revision that comments that out for 0.1.  We don't have any settings yet ;)

**Comment by Graeme22** [comment]
where does it store the files?

**Comment by HR** [comment]
for what?

**Comment by ferndot** [comment]
It stores them in the sdcard/documents directory.

**Comment by Graeme22** [comment]
I can't find them...

**Comment by Graeme22** [comment]
also, where do u create the files? in the browser? is so, how come I cant type anything anywhere?

**Comment by ferndot** [comment]
Oh, you run FireText on Firefox OS.  You can get the simulator <a href="https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi">here</a>.

FireText won't work on desktop Firefox.

**Comment by Graeme22** [comment]
I was running it on firefox, though! r u saying that u need to get the actual add-on to use it?

**Comment by Graeme22** [comment]
also, wouldn’t b cool for the favicon to be a word burning up?

**Comment by HR** [comment]
It is an app that isn't (till now) supposed to run in browser, it is a packaged application. Here is the simulator(add-on): https://addons.mozilla.org/en-US/firefox/addon/firefox-os-simulator/

**Comment by ferndot** [comment]
About the first question, yes, unfortunately you will.  The Device Storage API is not currently supported on desktop Firefox.  We may make a desktop version of FireText that uses the File API, but we are focusing on the mobile app right now.

As to the second question, you can see our icon when you instal FireText on the Simulator.  We probably should add a meta icon too (I'll do it in the next commit).

Hope this helps :)

**Comment by HR** [comment]
I think you should start from here: https://marketplace.firefox.com/developers/docs/quick_start

**Comment by Graeme22** [comment]
I know there’s already an icon, I was suggesting a different one. Anyway, thx!

**Comment by Graeme22** [comment]
why are we focusing on the mobile app? who’s going to write a document on their phone? and even if someone did, wouldn't it be better 4 it to b on a computer rather than a mobile device? I know you're already far into it, but I think that our priority should be for desktop firefox.

**Comment by HR** [comment]
The main focus here is mobility; the option of editing documents on the go anywhere and as technology is progressing, the future seems only to consist form mobile devices (smartphones and tablets). But you're right in a sense and hopefully we are going to release a desktop version soon. With the collaboration feature, it means that the app will be hosted and cloud based (vital thought for future), thus we should also implement it to desktop thereby creating a social network such as github but with word processing in mind instead of coding.

**Comment by HR** [comment]
But that is laters.

**Comment by Graeme22** [comment]
my bro has an iPod, maybe I could get him to try it on that? also, could u tell me the names of the app(s) he would need to get to use it?

**Comment by HR** [comment]
You are talking about IOS which is a whole different OS (native apps in objective C), what kind of app to use it? Just a general question, how much of Firefox OS do you understand? Or are you just a beginner(to general software, os, ...)? And what programming languages do you know?

**Comment by Graeme22** [comment]
im just a beginner when it comes to programming apps for firefox.  the reason I joined this group is ‘cause my favorite browser is firefox and I like to program, sooooo...

**Comment by HR** [comment]
Ok buddy, we can help you but the things you gotta learn the basics before moving to the hard stuff and you should read all the get starting stuff: https://marketplace.firefox.com/developers/docs/fundamentals

**Comment by ferndot** [comment]
It's ok, basically what we are making is a web-based word processor for 
Firefox OS.  It uses some webapis 
https://developer.mozilla.org/docs/webapi that are not supported on 
desktop computers (yet).

**Comment by logan-r** [comment]
When I go to https://marketplace.firefox.com/app/firetext/ it still says "This app is awaiting review." Does anybody know how long it's going to take?

**Comment by ferndot** [comment]
I asked on IRC, and they said that the usual review time is 4 weeks :(

**Comment by HR** [comment]
sooo long....? why?

**Comment by ferndot** [comment]
They probably have a lot of apps to review, and each app can take a while...  Also, there are not many reviewers yet.
