### ISSUE TITLE
Prompted to Give FireText Accesses to Memory Card Multiple Times

### ISSUE THREAD

**Issue by logan-r** [codexa/firetext#42]
I think it has something to do with `loadFile`.

**Comment by ferndot** [comment]
?

**Comment by logan-r** [comment]
Sorry, I accidentally clicked submit before I finished typing.

**Comment by ferndot** [comment]
Maybe, could you wait a sec before fixing this?  I am almost done with a workaround for #13

**Comment by logan-r** [comment]
Okay, I'm still just trying to figure out why it is prompting the user multiple times.

**Comment by ferndot** [comment]
Done, you can take it now!

**Comment by logan-r** [comment]
**Update:** The bug is caused by `docsInFolder`.

**Comment by ferndot** [comment]
I fixed this accidentally in https://github.com/Codexa/FireText/commit/3938dca7cf70c079e73ab7f8de805057c751a262.

Guess I killed two birds with one stone (don't tell the environmentalists).

**Comment by logan-r** [comment]
Great!
