### ISSUE TITLE
Codexa logo!

### ISSUE THREAD

**Issue by HR** [codexa/firetext#43]
I have made the Codexa logo now, check it out and give feedback(and follow on google+)
Full res: https://www.dropbox.com/s/4jaipjoebhupf5z/codexa.png
https://github.com/Codexa
https://plus.google.com/u/0/b/104254292240828026368/104254292240828026368/posts

**Comment by ferndot** [comment]
Nice :)

**Comment by logan-r** [comment]
Cool logo! :smile:
