### ISSUE TITLE
Add dialog callback function not working

### ISSUE THREAD

**Issue by logan-r** [codexa/firetext#46]
The add dialog's callback function (which adds the new file to the recent docs list and then opens it) isn't working.

**Comment by ferndot** [comment]
It broke again?

**Comment by HR** [comment]
There is an additional problem in general, that is that the html is parsed even in the description of the document at the welcome screen, which it shouldn't.

**Comment by ferndot** [comment]
That was intended, the html in the description messed things up.

**Comment by HR** [comment]
To parse html in the description?

**Comment by ferndot** [comment]
Yes, see https://github.com/Codexa/FireText/commit/17f7e748bba3eee6c13bb03f5bf636dd2b576c82.

We don't want headers, images, tables, and things in the description.

**Comment by HR** [comment]
You should parse it but remove any styles, what do you think?

**Comment by ferndot** [comment]
Then what would be the point?

**Comment by HR** [comment]
The styling could ruin the app, what if someone sets font to larger or tries to parse any other styling that would interfere in the UI?

**Comment by ferndot** [comment]
Oh, I think we are misunderstanding each other :D

Currently, it is just printing the text content of the file.  I don't think we should change this as the description is only supposed to be text anyway, and it could cause a security vulnerability like in #7.

**Comment by HR** [comment]
Go in app and type this for example: `<h1 style="color:red; font-size: 2em;">hi<h1>` and you see the styling being applied that ruins the UI

**Comment by ferndot** [comment]
Oh, let me see something...

**Comment by ferndot** [comment]
That was easy to fix: https://github.com/Codexa/FireText/commit/a88255f360f3d49534c1c75170807156eb8f7cd8.

Don't worry if it looks hacky, it will work!

**Comment by ferndot** [comment]
...this bug...

**Comment by HR** [comment]
1 day to go...

**Comment by ferndot** [comment]
oh dear!

**Comment by ferndot** [comment]
I was right!

**Comment by ferndot** [comment]
Almost have this fixed :)

**Comment by logan-r** [comment]
Great!

**Comment by ferndot** [comment]
We can ship after I improve the first load experience with one more commit!

**Comment by HR** [comment]
wait I have to add one more thing as well before we ship!

**Comment by ferndot** [comment]
Yes, what is it?

**Comment by HR** [comment]
done, added custom title font (logo)

**Comment by ferndot** [comment]
oh :D

**Comment by HR** [comment]
hooray, we're done.

**Comment by HR** [comment]
should I upload it to mozilla?

**Comment by ferndot** [comment]
I am getting one of the gaia devs to test it in a few mins, so please don't upload yet.

**Comment by HR** [comment]
ok, and I test it in the validator: https://marketplace.firefox.com/developers/validator

**Comment by HR** [comment]
1 warning, 0 errors: https://marketplace.firefox.com/developers/upload/f751bdebc99a43a29b56f8720b119284

**Comment by ferndot** [comment]
I am packaging it in a special way to avoid that issue.  **Don't** delete that file.  It keeps other system files from being stored in the repo.

**Comment by HR** [comment]
Oh, I deleted the hidden file, now its fine: 0 warning, 0 errors: https://marketplace.firefox.com/developers/upload/4d1bbfc6eaeb44a5b5c5804cd8141d57

**Comment by HR** [comment]
I didn't delete any file from repo, I deleted from .zip after I downloaded a copy:)

**Comment by ferndot** [comment]
Phew :)

**Comment by HR** [comment]
have gaia devs tested it yet?

**Comment by ferndot** [comment]
He said that he would do it in a bit.  We are on <a href="ircs://moznet/gaia">ircs://moznet/gaia</a>.

**Comment by ferndot** [comment]
I uploaded it to the marketplace!  @HRanDEV, can you set up redirects for our codexa.app@gmail.com email so that it will send me copies of messages received?

**Comment by logan-r** [comment]
@Joshua-S Awesome! But... I don't see firetext in the marketplace. :frowning: Is there some sort of verification process before it gets published?

@HRanDEV Could you set up an email redirect for me too?

**Comment by HR** [comment]
here is the URL: https://marketplace.firefox.com/app/firetext/

**Comment by HR** [comment]
Ok, I will

**Comment by HR** [comment]
I need your confirmation codes(send via email) to forward emails.

**Comment by logan-r** [comment]
@HRanDEV Thanks for the link and I just submitted my confirmation code!

**Comment by ferndot** [comment]
@HRanDEV I sent the code!
