### ISSUE TITLE
Settings!

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#48]
This region will be accessed from the welcome region and sidebar.

It will contain preferences like the user's dropbox id.

**Note:** This feature is for 0.2+, please develop it in that branch.

**Comment by HR** [comment]
added setting button to toolbar in sidebar https://github.com/Codexa/FireText/commit/aedccd8284d2b5b0cc10d53c47083ee38c98ce62

**Comment by ferndot** [comment]
Great!

**Comment by ferndot** [comment]
Added dialog, track individual settings with their corresponding issues.
