### ISSUE TITLE
New Tab UI

### ISSUE THREAD

**Issue by HR** [codexa/firetext#49]
Now that we have a base, I think we should add the tab UI for multi-file editing (idea continued from request of removing "editing...") of open documents, the filename in text (no extension for now - casual consumer oriented). I think that this would make the app a lot more useful and collaborative. What do you think?(maybe for v2?)
// Basic Preview: https://www.dropbox.com/s/n784pn9tmo1m9az/tabUI.png

Finals:
Design mode: https://www.dropbox.com/s/00e7xnm23gthict/tabUI-design_mode.png
Edit mode: https://www.dropbox.com/s/vu0rl8uj2engvin/tabUI-edit_mode.png

**Comment by ferndot** [comment]
Sounds good, but I think before we go any farther, we should make some 
mockups.  It is usually better do work with a design than to make it up 
as we go.

**Comment by HR** [comment]
ya sure, I'll try to design some...UIs

**Comment by HR** [comment]
here a preview(I made using PS): https://www.dropbox.com/s/n784pn9tmo1m9az/tabUI.png

**Comment by logan-r** [comment]
Looks awesome! How do you close a tab?

**Comment by HR** [comment]
Add a close button in sidebar maybe or toolbar?

**Comment by HR** [comment]
What do you think?

**Comment by logan-r** [comment]
We already have one in the sidebar, but it's not visible to the user at start. Maybe we could add a button on the toolbar.

**Comment by HR** [comment]
What about double tapping the tab to close it or swipe it(use gestures)?

**Comment by logan-r** [comment]
Maybe swipe up to close a document?

**Comment by ferndot** [comment]
Sounds intriguing!

**Comment by ferndot** [comment]
I am working on this now!

**Comment by ferndot** [comment]
Need to change the tab switching to js with next commit :)

**Comment by ferndot** [comment]
@Logi0 is it ok if I remove the back button to conform to the mockups?  The welcome region will now only be shown when there is no recent file to open.

**Comment by HR** [comment]
You can leave the back button if you want, but the app should open the last opened file(last session - use local cache) at startup. Also, filters are used to switch between open files/open folder however the tabs are used to switch between the modes(design, raw/edit - should be icons)

**Comment by ferndot** [comment]
@HRanDEV I don't think that we should do the open file tabs thing (at least on mobile).  I have already had to label the app incompatible with landscape view because of a lack of space.

But the rest sounds great.

**Comment by HR** [comment]
Ok, maybe do something better laters

**Comment by logan-r** [comment]
The back button is good because it minimizes the number of taps required to get back to the home screen while not taking up much spaces.
