### ISSUE TITLE
Editing in the editor

### ISSUE THREAD

**Issue by HR** [codexa/firetext#50]
We have agreed that this is a general consumer "word processor", so why show raw HTML as barely anyone in the public knows HTML. And what is the point of allowing italic, bold and underline format when it is going to be saved in plain text?

What if we have a design mode (editing through UI for normal consumers) and then have a edit mode where all the design(formatting) is being written in HTML (design mode is just parsed HTML and people who know HTML can edit it if they want(switch through toolbar). And the .txt is just gonna be plain text without any format.

The editing tools for designing(bold, italic, underline, list, position) will probably be in the sidebar

Designs of screens:
Design mode: https://www.dropbox.com/s/00e7xnm23gthict/tabUI-design_mode.png
Edit mode: https://www.dropbox.com/s/vu0rl8uj2engvin/tabUI-edit_mode.png

**Comment by logan-r** [comment]
I'm kind of confused. Where do we show raw HTML? The formatting is done in HTML but all the user sees is **this** not <b>this</b>

**Comment by HR** [comment]
Look there are two modes: design and code. So kind of like in dreamweaver, you can either design with graphical editing tool or code yourself (have tabs below). As probably 75% of people probably won't know html, we need it to target all audiences with different levels of knowledge of computing. And as the description says it is a "word processor" mainly (e.g. MS Word - anyone can work with UI without any code). If we don't integrate the "design" mode then we are going to miss by a lot greater than 75% of firefox os consumers. In the design mode the user will **this** but in the edit mode there is this (being live written by program via UI from design view) <b>this</b>.

**Comment by HR** [comment]
Designed the screens:
Design mode: https://www.dropbox.com/s/00e7xnm23gthict/tabUI-design_mode.png
Edit mode: https://www.dropbox.com/s/vu0rl8uj2engvin/tabUI-edit_mode.png

**Comment by ferndot** [comment]
Sounds cool, we already have design mode, and we can implement edit mode pretty easily.  Please wait for 0.2 though, as we want to release 0.1 this week, so that means a feature freeze.

**Comment by logan-r** [comment]
I think @HRanDEV does have a point. If people see `.html` they probably will start typing: `<div class="...`, etc. To solve this I could quickly add `.odml` support (just for the `<content>` part, not `<info>`). It would take me less than an hour to add this feature, but since we are so close to releasing version 0.1, should I?

**Comment by HR** [comment]
Yes, I think you should because we have made the app and extension so the extension should come from v1 (unique thing) to make people aware of the format from now.

**Comment by ferndot** [comment]
Whatever you think is best.

**Comment by ferndot** [comment]
Fixed this one too!
