### ISSUE TITLE
Delete confirm dialog doesn't work

### ISSUE THREAD

**Issue by logan-r** [codexa/firetext#51]
I just tested the app and it all works great, except for when a user deletes files, the confirm delete dialog doesn't appear. On a touch screen it would be all to easy to accidentally delete important files.

**Comment by HR** [comment]
I can't select separate files to delete, I can only select all files(button)

**Comment by ferndot** [comment]
@HRanDEV Can you file a new issue for that?

**Comment by HR** [comment]
what do you mean by "file" a new issue?

**Comment by ferndot** [comment]
I mean to "create a new issue."
