### ISSUE TITLE
New app idea

### ISSUE THREAD

**Issue by HR** [codexa/firetext#52]
I was thinking about a small new game app build with simple dynamics called "SpaceX rocket". It is about controlling a space rocket with gestures and motions mainly. I have most of the graphics ready (but will develop the rest). There is a lot more to it, but what do you think about the idea?

**Comment by ferndot** [comment]
Sounds cool, you can create a repo for experimentation under Codexa.  
Please don't leave the FireText project though :(

**Comment by HR** [comment]
No, I won't. It is another Codexa app!

**Comment by logan-r** [comment]
Awesome! I've got some experience with HTML5 gamedev (see [HMTL5-Games/vilify](https://github.com/HTML5-Games/vilify)).

**Comment by ferndot** [comment]
@Graeme22 if you want to work on this, I'll add you to the team.

**Comment by Graeme22** [comment]
if its not for mobile devices only, I should b able to help out a lot more.
