### ISSUE TITLE
Syntax highlighting in the raw editor

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#58]
It would be cool to have syntax highlighting and auto indentation in the raw editor!
Syntax highlighter(js): https://code.google.com/p/google-code-prettify/

**Comment by logan-r** [comment]
I'll work on that!

**Comment by ferndot** [comment]
Great!

**Comment by HR** [comment]
Hey, we just have to implement this: https://code.google.com/p/google-code-prettify/

**Comment by ferndot** [comment]
@Logi0 are you still working on this?

**Comment by logan-r** [comment]
Yep. I'm kind of confused about how to implement it, though.

**Comment by HR** [comment]
Just place `<pre>` tags and parse after them

**Comment by logan-r** [comment]
Yeah, I tried that... I can't quite seem to get it to work.

**Comment by ferndot** [comment]
I'll take a look at it if that is ok.

**Comment by logan-r** [comment]
Great!

**Comment by HR** [comment]
What is the progress on this?

**Comment by ferndot** [comment]
I am having a little trouble, going to ask on IRC sometime.  My problem is that when I insert the highlighted html into the raw editor, it causes the cursor to jump around.

**Comment by ferndot** [comment]
Almost have this, still need to figure out how to prettyPrint dynamically.

**Comment by HR** [comment]
great

**Comment by ferndot** [comment]
I did it (uh hu uh hu)!  The only downside is that code will not highlight while typing.  You have to blur the raw editor first.

**Comment by HR** [comment]
We'll solve that later but well done.

**Comment by logan-r** [comment]
Great job!
