### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by HR** [codexa/firetext#59]
We should have a auto-save feature like most app and softwares do now, so the even if the battery runs low that your files are saved. It should save after every change automatically without disturbing the user.

**Comment by ferndot** [comment]
Why did you close this?

**Comment by HR** [comment]
oh, so you just added the auto save preferences?

**Comment by ferndot** [comment]
Yes, autosave itself shouldn't be hard though...

**Comment by ferndot** [comment]
@Logi0 I need your help with localStorage, I'm not doing something right.

Thanks in advance!

**Comment by logan-r** [comment]
@Joshua-S Does https://github.com/Codexa/FireText/commit/15c5bc27e3d828713ed1364186db3b5f6a5478a9 help?

**Comment by ferndot** [comment]
Hmm, something broke the Recent Docs thing...

**Comment by ferndot** [comment]
Sorry @Logi0, I had to revert that commit...  The part that I am having trouble with is https://github.com/Codexa/FireText/blob/0.2/js/firetext.js#L731-L768.

**Comment by ferndot** [comment]
:crying_cat_face:  The only thing blocking this is the settings issue.

**Comment by ferndot** [comment]
Yay!!!
