### ISSUE TITLE
Add way to open files.

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#6]
This bug covers two different things:
      1. The open dialog must show the contents of the sdcard (storage) "Documents" Folder as you cannot view that with a file input. 
      2. FireText should handle opening a file (editor.innerHTML = document contents;, titleElement = filename;, etc...)

Note: Problem number two has moved to bug #3

**Comment by logan-r** [comment]
I solved problem 2 with 7ffff345622208f9586224d760b82f808c7323c8 & 197905bfaa8087776ecd852c4904217bea43f73!

**Comment by ferndot** [comment]
Great!  I am looking up how to enumerate files in a directory.

**Comment by ferndot** [comment]
(@Logi0 said in another issue)

Checkout https://developer.mozilla.org/en-US/docs/WebAPI/Device_Storage?redirectlocale=en-US&redirectslug=WebAPI%2FDevice_Storage_API.

> `deviceStorage.enumerate([directory])`
>    Returns a DeviceStorageCursor that enumerates Files in the storage or the directory (string) passed as argument
> 
> `deviceStorage.enumerateEditable([directory])`
>    Same as .enumerate, but enumerates FileHandles

**Comment by logan-r** [comment]
Don't know how I did that... :laughing:

**Comment by ferndot** [comment]
I think there was some sort of regression introduced in https://github.com/Joshua-S/FireText/commit/86cf47dac253c6a129d2352e95b8d46c9eb8aa67.

I have to go, will figure it out tomorrow.

**Comment by ferndot** [comment]
@Logi0 fixed the regression with https://github.com/Joshua-S/FireText!

**Comment by ferndot** [comment]
Problem two has moved to issue #3.
