### ISSUE TITLE
Opensource API security

### ISSUE THREAD

**Issue by HR** [codexa/firetext#66]
If Firetext is open source, then we have a problem in our APIs that need our crucial client ids and client secret that could be misused. So there is a security issue

**Comment by ferndot** [comment]
We encoded our dropbox id, so it isn't as critical.  But if there is a way to further encode it, please do that.

**Comment by HR** [comment]
How? with custom algorithms?

**Comment by ferndot** [comment]
I don't really think that it will be an issue, and if it is, we can blacklist bad apps.  Can you encode the Google Drive key?

**Comment by HR** [comment]
How did you encode it?

**Comment by ferndot** [comment]
Dropbox provided a secret+id encoder on the developer site :)
