### ISSUE TITLE
Formatting 

### ISSUE THREAD

**Issue by logan-r** [codexa/firetext#67]
Besides bold, italic, and underline, what formatting features should we support?

**Comment by ferndot** [comment]
In v0.2 we could add bullets/numbering and font-size.  Images/tables could come in v0.3.

**Comment by logan-r** [comment]
What about font and font-color?

**Comment by ferndot** [comment]
Those too :)

To see what is supported, you can visit https://developer.mozilla.org/en/docs/Rich-Text_Editing_in_Mozilla.  I love Midas!

**Comment by HR** [comment]
Firetext is a "word processor", therefore we should concentrate more on text formatting and cloud comes afterwards so we should add as many tools as possible.

**Comment by ferndot** [comment]
The hard part is fitting it all on a 380x420px screen :(

**Comment by HR** [comment]
well, you gotta be responsive for a word processor

**Comment by ferndot** [comment]
Ya...  If you open individual bugs for each, I'll work on them.

**Comment by ferndot** [comment]
This is covered in #69.
