### ISSUE TITLE
Bullets/Numbering

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#68]
Add support for bullets/numbering and aligning text in html/docx files.

**Comment by ferndot** [comment]
@HRanDEV can you make an icon for each (base yours off of the existing toolbar icons, and the design principles here https://www.mozilla.org/en-US/styleguide/products/firefoxos/action-icons/).

**Comment by HR** [comment]
Sure, but I am going to convert them into base64 and  also tell me all the other icons that we need need.

**Comment by ferndot** [comment]
Font-color, font-size, superscript, subscript, table, image, email, text, help.

Those are what I can think of right now.

**Comment by HR** [comment]
@Logi0 can you implement this and other tools while I and @Joshua-S are working on the APIs, I will send all the icon needed.

**Comment by ferndot** [comment]
I can finish this :)

**Comment by HR** [comment]
ok

**Comment by ferndot** [comment]
Fixed by https://github.com/Codexa/FireText/commit/3fc629f790a44bba0b47958957fb132660e9383f
