### ISSUE TITLE
Word Processor features

### ISSUE THREAD

**Issue by HR** [codexa/firetext#69]
Here are some features to work on.  Check when done:
- [x] Wordwrap: automatic arrangement of text in lines of specified length without the necessity of touching the return key.
- [ ] Discretionary Hyphenation: option of inserting a hyphen to break a word that ends a line:  the hyphen does not print if later editing moves the word to the middle of a line.
- [x] Justification: automatic alignment of text to both the left and right margins.
- [ ] Adjustment: realignment of text to new margin and tab settings.
- [ ] Alignment: positioning text or numbers to specified margin and tab settings.
- [ ] Decimal Alignment: positioning columns of numbers with the decimal points vertically aligned.
- [x] Indents: the setting of temporary margins within a document differing from the primary margins used.
- [x] Centering text on a line.
- [x] Insertion: the entry of new text within previously typed material without erasing the existing material.
- [x] Deletion: erasure of text from the screen, or of whole documents from the disk.
- [ ] Search and Replace: moving directly to specified words or parts of words within a document and replacing them with different words or word portions.
- [x] Copying or Cutting: the duplication or moving of blocks of text within a document.
- [x] Automatic Spelling Checker and Corrector.  Program that compares words in the text against an on-line dictionary, flagging items not found in the dictionary and offering alternative spellings and a means of correcting the errors.  (This is built into the keyboard).

**Comment by ferndot** [comment]
AAHHH :fearful:, I mean, you will have to make icons for _most_ of these :tongue:

**Comment by HR** [comment]
yup, I might try to find an icon set (with CC 3.0)

**Comment by logan-r** [comment]
Isn't copy, cut, & paste implemented by default?

**Comment by ferndot** [comment]
Not in gaia, I think we will need a clipboard permission.

**Comment by HR** [comment]
Full list here: https://github.com/Codexa/Firetext/issues/106

**Comment by ferndot** [comment]
Moved to #106
