### ISSUE TITLE
Remove Scripts from Documents

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#7]
As most of our documents will be stored and shown in a HTML based format, it would be a major security vulnerability to allow scripts in documents.

It also might prevent the app from being approved.

**Comment by HR** [comment]
Do we really need to support .html?

**Comment by ferndot** [comment]
Well, it seems like the easiest way to go for the initial version.  It would delay the development process a lot to have to implement a way to parse rtfs or another format.  The editor can only edit html, so it is the most direct way of saving a document.

What did you have in mind?

**Comment by HR** [comment]
It is not really a code editor, it is rather a text editor what about .doc or .docx (loads of people use ms office and want to edit on the go).

**Comment by ferndot** [comment]
Do you know where we can find the format specs for doc/docx?

**Comment by HR** [comment]
maybe this will help:
http://openxmlviewer.codeplex.com/

**Comment by HR** [comment]
Use iframe to overcome that problem(mozilla uses it)
e.g.
`<iframe height="480" frameborder="1" width="320" src="https://mdn.mozillademos.org/en-US/docs/Mozilla/Firefox_OS/UX/Building_blocks/Action_menu/Coding$samples/Without_title?revision=359599">#document<!DOCTYPE html><html><head></head><body><form id="sample-menu" onsubmit="return false;" data-type="action" role="dialog"><menu></menu></form></body></html></iframe>`

see here in developer console on demo: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/UX/Building_blocks/Action_menu/Coding

**Comment by ferndot** [comment]
@HRanDEV was that comment meant for https://github.com/Joshua-S/FireText/issues/9?

**Comment by HR** [comment]
no, for keeping html contained to prevent security risks

**Comment by ferndot** [comment]
Just changed the div to an iframe with these commits: https://github.com/Joshua-S/FireText/commit/99f8dc1360a0b1889ca36d6513184b9a3827b14b, https://github.com/Joshua-S/FireText/commit/d57d3e2eb10b321bf48eb4663985509bba1a54e2, https://github.com/Joshua-S/FireText/commit/b2a30424a76236798075ae05d3b9055f09a0f349.

Need to fix the formatting buttons to format the correct thing.

**Comment by ferndot** [comment]
I think this issue is fixed!
