### ISSUE TITLE
User change log

### ISSUE THREAD

**Issue by HR** [codexa/firetext#71]
We need to log any changes to the state to send for error report.

**Comment by ferndot** [comment]
I think that this needs to be an opt-in feature.  Users will not download FireText otherwise.

**Comment by HR** [comment]
Well all the others do it all the time(e.g. Google), all we will do(like others) have the option for sending usage data checked in settings and just alert the user once on first startup with a data privacy policy of the user(e.g. no personal info will be passed on). And we will tell them that it is only to enhance the app and future development purposes.

**Comment by ferndot** [comment]
When we log, we will do it anonymously.  We should just collect actual program stats and non-personal system info (e.g. os, hardware).

**Comment by HR** [comment]
obviously, the client id(which will have all other data in db) will be included. Not hardware but software

**Comment by HR** [comment]
Sorry, but I think that I going to use PHP due to the implications in js (no native support for file creation)

**Comment by ferndot** [comment]
@HRanDEV and I have been talking, and now we are using Bugsense for analytics (more secure, faster, and nicer).

**Comment by HR** [comment]
ok, We'll remove this then

**Comment by ferndot** [comment]
I am committing the working code (that was super easy)!

**Comment by HR** [comment]
for the bugsense implementation?

**Comment by ferndot** [comment]
Yes, two lines of code, one script!

**Comment by HR** [comment]
:+1:

**Comment by ferndot** [comment]
I actually am going to wait to commit it until I hear back from Bugsense about API Key security.

**Comment by HR** [comment]
just DO NOT INCLUDE THE API IN TH PUBLIC REPO

**Comment by ferndot** [comment]
Aha!  We need to use two different keys for testing and release so errors don't get mixed.  That will make things nicer :)

**Comment by ferndot** [comment]
API Key is not included.
