### ISSUE TITLE
Save login sessions

### ISSUE THREAD

**Issue by HR** [codexa/firetext#72]
For users who login via API, how are we going to save the login tokens so that the user doesn't have to login in every time the app launches. Is that gonna be done using database(security).

**Comment by ferndot** [comment]
It will be done using local storage, and managed using the settings UI.

**Comment by HR** [comment]
We can use IndexedDB
https://developer.mozilla.org/en-US/docs/IndexedDB

**Comment by ferndot** [comment]
I have heard that IndexedDB is a little slow, does it have any major pros over localStorage?

**Comment by HR** [comment]
Indexedb is very stable

**Comment by HR** [comment]
And Indexedb is actually database which we need for server-client communication https://github.com/Codexa/FireText/issues/77

**Comment by HR** [comment]
Also on big thing is that localStorage is not scalable and works in very small bases(e.g. remembering form input temporary) with very small data that is not indexed or structured whereas Indexedb is scalable and works well with huge data that is structured(very important for sync between client and server).

**Comment by ferndot** [comment]
Ok

**Comment by HR** [comment]
check out the https://github.com/Codexa/FireText/issues/77

**Comment by ferndot** [comment]
I did :)

**Comment by HR** [comment]
That is the future, but we also have to concentrate(more) on editing tools.

**Comment by ferndot** [comment]
I just found out that OAuth does this automatically.
