### ISSUE TITLE
New Wallpapers

### ISSUE THREAD

**Issue by HR** [codexa/firetext#74]
New Wallpapers that I created, only use the FinalWallpaper.png for social media and other public publishing. I have already changed the picture on google+ page.
Download link: https://www.dropbox.com/s/bq4iqfi5alw7kaf/Firetext_icon.zip
Accounts:
https://plus.google.com/u/1/b/109856376316208647902/109856376316208647902/posts
https://twitter.com/FireText_App

**Comment by logan-r** [comment]
Looks awesome!

**Comment by ferndot** [comment]
Wow, you did a really good job :)

**Comment by HR** [comment]
Thanks :), we still have to do a lot.

**Comment by ferndot** [comment]
Btw guys, I just added full screen mode to FireText :)

(https://github.com/Codexa/FireText/commit/2dc88734478b4bcfe5abb9fc78482910708ec867)
