### ISSUE TITLE
Cloud9 Codexa Firetext workspace

### ISSUE THREAD

**Issue by HR** [codexa/firetext#75]
I've created a firetext workspace on the Cloud9 IDE: http://c9.io/codexa/firetext
I've already cloned the git repo so just sign in with your GH it hub account and start working.

**Comment by ferndot** [comment]
Great, thank you.  Used cloud9 on the space apps challenge :)

Just as a side note, please don't mark issues feature/enhancement that aren't code related.  Thanks!
