### ISSUE TITLE
Updated social media covers and wallpapers

### ISSUE THREAD

**Issue by HR** [codexa/firetext#76]
I've updated all the covers and even made one for codexa besides the firetext cover for youtube, twitter and google+:

Codexa:

> Google+: https://plus.google.com/u/0/104254292240828026368/posts
> YouTube: http://www.youtube.com/user/CodexaApps
> Twitter: https://twitter.com/CodexaApps

Firetext:

> Google+: https://plus.google.com/u/0/109856376316208647902/posts
> Youtube: http://www.youtube.com/user/FireTextApp
> Twitter: https://twitter.com/FireText_App

Please share the links and follow.

**Comment by ferndot** [comment]
Great, thanks!
