### ISSUE TITLE
Google drive storage unified across all sevices

### ISSUE THREAD

**Issue by HR** [codexa/firetext#78]
This is just news. Google drive has now been unified across the all Google services
https://www.youtube.com/watch?v=wIUWo9dSuO4
Link to update, now we can access all other data as well(e.g. email attachments)

**Comment by HR** [comment]
I am going to finish the Google API soon as I know understand how to implement this after reading tons of documentation that wasn't much relevent to this kind of app, just need a bit more time.

**Comment by ferndot** [comment]
No big rush :)
