### ISSUE TITLE
FireText or Firetext

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#79]
I have noticed both being used, so we need to specify which we want.

Firetext is the one that I am leaning towards, you?

**Comment by HR** [comment]
Firetext, have already made all the media(wallpaper, etc.)

**Comment by ferndot** [comment]
k

**Comment by HR** [comment]
so the short-cut is "Ft" like the extension icon

**Comment by ferndot** [comment]
I will fix all casings in the source code.

**Comment by HR** [comment]
k

**Comment by ferndot** [comment]
Reopened until fixed.

**Comment by logan-r** [comment]
Yeah, Firetext is better.

**Comment by HR** [comment]
I think we are done here.
