### ISSUE TITLE
Firetext Webapp

### ISSUE THREAD

**Issue by HR** [codexa/firetext#80]
Since we are planning to implement this on multiple platforms(Ubuntu OS, Android OS and even IOS), it is the best and easiest way to set firetext up as a mobile webapp. we've have http://codexa-firetext.appspot.com server that we can use. Then we can easily maintain and port to all platform. We'll then also have a more dynamic communication flow with http://dbstorage-firetext.appspot.com

What do you think?

**Comment by ferndot** [comment]
Are you meaning to change Firetext from a packaged app to a hosted app?  We can't do that on FxOS, because the storage APIs require it to be a packaged app.  But it would be good to host a copy (maybe using the File API instead of deviceStorage).

**Comment by HR** [comment]
I'm talking about creating an infrastructure and a universal UI. When we create an infrastructure, we'll have the basic system configured however we will then adapt to the platform if needed for APIs such as on Firefox OS. And I'll start designing a mockup/template for a universal Firetext UI. We could use File API, but remember the main point of doing this is because it will save us a ton of work(designing for each platform separately), we will be able to maintain it a lot better(!important) and we will have one unified system that we can easily track for analytics therewith also scale application.

**Comment by ferndot** [comment]
Yes, that is a very good idea.  Can you design mockups for mobile (least features because of space problems), tablet (more features), and desktop (all features)?

**Comment by ferndot** [comment]
Oops.

**Comment by HR** [comment]
I am working on this now, gotta look at design patterns and enhancing UX

**Comment by ferndot** [comment]
Great, with my recent work on File IO, we may eventually be able to use the same app globally (we just alter the UI for different screen sizes and OSs).  I can implement different APIs for file system management, and just select the supported one.

**Comment by HR** [comment]
The UI will stay the same across all platform (like other apps(es) such as twitter) but mechanic with dealing File I/O based on platform will change. But there will still be one main web application of Firetext that will run hybridity (hlf native > File IO and half web app > client-server communication).

**Comment by ferndot** [comment]
Also, in the future I am implementing Firebase.  Maybe this could be one of our first collaborative editing services?

**Comment by ferndot** [comment]
About the UI.  We need a desktop UI and a mobile UI, they can't be the same on both desktop and mobile.

**Comment by HR** [comment]
Obviously but the colour scheme has to stay consistent and the feel of it. What if we also name our collaborative network "Firebase" or can you think of something better.

**Comment by ferndot** [comment]
Unfortunately, Firebase is already taken; it is a company :(

Otherwise...

**Comment by HR** [comment]
Please think of a name

**Comment by ferndot** [comment]
Will do :)

**Comment by HR** [comment]
thanks

**Comment by jackd1** [comment]
I think, instead of loading separate apps, we could design the ui to adapt to the size of the screen, adding more features for larger screens and less features for smaller screens, we also need to support touch ans click events for all screen sizes to best support some newer screens that support touch, even cases where someone may be using both touch and the mouse.

**Comment by ferndot** [comment]
@jackd1 you are perfectly correct, and if you take a look at the code, you will see that that is exactly what we are doing.  Now Android and other OSs that don't run native webapps may be a little different, or we may just create a modal for each that contains a rendering frame (or use XUL).

**Comment by jackd1** [comment]
Ok, great, sorry, still looking through the code.

**Comment by ferndot** [comment]
np :wink:

**Comment by HR** [comment]
We are looking forward to a hybrid app really in which the functionality is native

**Comment by jackd1** [comment]
So which apis are we using?  It looks like IndexedDB will provide the most support, the other option would be to use the FileSystem API.

**Comment by HR** [comment]
Indexeddb to store metadata, commits, ciomments, account info ( incl.auth tokens, client id, etc) and other info for Fireanalytic as well as Firesearch user data (i.e. user pref). Filesystem API for IO operations (inlc. backup to cloud) and internal storage for documents.

**Comment by jackd1** [comment]
Ok, but what are we going to use for storing documents on devices other than FirefoxOS

**Comment by HR** [comment]
All other system would also have similar Filesystem APIs we are going to write cross platform code so that it works on all Mobile OS(es). BTW we are going to make a real social network that is all about consumer cloud word processing and much more intuitive then Google docs or MS Word(will have more features). That we want to get at least basic word processing features.

**Comment by ferndot** [comment]
This is old and inactive.
