### ISSUE TITLE
Implement Night Mode

### ISSUE THREAD

**Issue by HR** [codexa/firetext#82]
Invert the colors to allow editing even at night(for me and other night owls).

**Comment by ferndot** [comment]
Sounds cool, could you make UI svgs into a font so that we don't have to make new icons for each color scheme?

**Comment by HR** [comment]
I will try to.

**Comment by ferndot** [comment]
We can use the Light Event API to detect ambient light and auto-change this.  See: https://developer.mozilla.org/en-US/docs/WebAPI/Using_Light_Events.

To make this more efficient, and use less code, we can use the invert filter to do all of the style changes.

**Comment by logan-r** [comment]
Can I take this issue?

**Comment by ferndot** [comment]
If only major browsers could implement the filter property :(

I am having to make a separate stylesheet.

**Comment by HR** [comment]
I was thinking about keeping only one set of icons and using them across both themes

**Comment by ferndot** [comment]
Yes, and invert would have done that.  But since we need to do a stylesheet, could you design a mockup please?

**Comment by ferndot** [comment]
Just got a device to test this on =)
