### ISSUE TITLE
Future of Firetext: Profile Integration Preview

### ISSUE THREAD

**Issue by HR** [codexa/firetext#84]
So I designed new UI for the future version of Firetext(v0.3) that illustrates the actual Firtext vision of to an extent.
https://www.dropbox.com/s/ey5wt1p4k94bjnv/tabUIprofile.png

I worked hard to make it suite so tell me what to add.
BTW Firelit basically means changes made(like commit in git)
What do you think?

**Comment by ferndot** [comment]
Awesome!  I hope we can implement that by v. 1.0 :)

**Comment by logan-r** [comment]
Looks great! What does "Firelit" mean thought?

**Comment by ferndot** [comment]
Read his description above ^.

**Comment by logan-r** [comment]
Oh, :laughing:

**Comment by ferndot** [comment]
Closing as we have all seen this :)
