### ISSUE TITLE
Fit all tools in

### ISSUE THREAD

**Issue by HR** [codexa/firetext#85]
So I had an Idea that would enable us to have all tools(about 90% min.- depends on amount of tools). The idea is that we will have two states: edit and format. The edit mode will have keyboard enabled an users can use very basic tools or most used tools. But the format mode won't have a keyboard and instead have only tools(in location where keyboard goes). The switching will be very prompt with just a swipe to left or choosing a custom keyboard. And this will be mostly for mobile phones. This is to target all users in market and to make app unique.

UI Mockup: https://www.dropbox.com/s/2wvyj9uynuhrfcf/main.png

**Comment by ferndot** [comment]
Can you design a mockup of this.  An idea that I had was to keep the toolbar, but make it function like the pinned apps bar on the homescreen (swipe your finger to scroll through the tools).

**Comment by HR** [comment]
Ok, but your idea is not very practical when you have 12 or more tools(hard to get overview - bad for UX).

**Comment by HR** [comment]
Sorry for being late but here it is the mockup: https://www.dropbox.com/s/2wvyj9uynuhrfcf/main.png

**Comment by HR** [comment]
We have #118 for this
