### ISSUE TITLE
Git Windows problem

### ISSUE THREAD

**Issue by HR** [codexa/firetext#86]
I've been getting a problem after cloning the repo every-time I try to push and pull. I can't even sync with the GUI(fails).

```
fatal: https://github.com/Codexa/FireText.git/info/refs?service=git-upload-pack
not found: did you run git update-server-info on the server? 
```

I have run git update-server-info makes no difference. I have also tried to re-clone the source(updates but after clone same problem) re-installed the whole application(deleted all cache) Any Idea as what I could do?

**Comment by ferndot** [comment]
Yes, we renamed the repo to Firetext, and git is case sensitive.  Sorry, I should have warned you...

so it should be:
https://github.com/Codexa/Firetext.git

**Comment by HR** [comment]
thanks
