### ISSUE TITLE
Global Network Name

### ISSUE THREAD

**Issue by HR** [codexa/firetext#87]
For a global editing network, we need a global name such as Github. We need a global name for the site from which we could maybe also create specialist term like "Firelit" for change in doc. More like Wordhub, Wordalliance, something unique, short and meaningful that summarizes its aims: "Collaborative social word processing".

**Comment by ferndot** [comment]
Firelit sounds cool.

**Comment by HR** [comment]
A bit more universal and professional(nothing with fire > irrelevant symbol for collaboration and word processing).

**Comment by HR** [comment]
More ideas needed! Come on, be creative!

**Comment by HR** [comment]
OK for now the network name will be Firetext
