### ISSUE TITLE
Firetext divesity Banner

### ISSUE THREAD

**Issue by HR** [codexa/firetext#88]
Just a banner I designed to promote the app.
https://www.dropbox.com/s/j16li20lqqkdisc/Firetextdl.png
https://www.dropbox.com/s/28efp9kmngzfii9/Firetextdiversity.png
What do you think about it?

**Comment by logan-r** [comment]
Looks great! Where are we going to use these? On firetext.co.nf?

**Comment by HR** [comment]
yup and social media
