### ISSUE TITLE
Create valid html

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#89]
We need to create a small parser to check if the document is in valid html form, and if not, convert it.  This would only be called on the save function.

**Comment by HR** [comment]
Why are we using spans for basic formatting such as making text bold, underline, italic instead of the native tags for such functions? (Is it part the security sandbox problem?)

**Comment by ferndot** [comment]
I can't remember the reason, I think it was so that Midas didn't create outdated tags and attributes (like align).

**Comment by HR** [comment]
We can remove the attributes and update them our self. It is important that we use native  HTML rather than CSS.

**Comment by ferndot** [comment]
You can fix that by deleting
https://github.com/Codexa/Firetext/blob/master/js/firetext.js#L586

**Comment by HR** [comment]
just delete that

**Comment by ferndot** [comment]
On thinking this over again, I realized that this should only be done on doc creation.  So easy!

**Comment by ferndot** [comment]
But I am moving this away from 0.3 because we just need to stabilize FT for the release.

**Comment by HR** [comment]
before releasing v0.3 please upload the final zip to dp an notify me

**Comment by ferndot** [comment]
Of course!  I have set the due date to the 5th, but we can extend it if needed.

I am working on a better pattern for future releases so that we won't spend 6 months per :)

**Comment by HR** [comment]
I have created v0.3 branch for production version

**Comment by ferndot** [comment]
Great!  All major features should now be worked on in the master branch.  We will merge bugfixes back, but not the entire branch.. 

Also for this version, I will probably minify the source for performance reasons before submitting it.

**Comment by ferndot** [comment]
Moving to #245
