### ISSUE TITLE
Adding a drawer

### ISSUE THREAD

**Issue by HR** [codexa/firetext#9]
What about a drawer for the user to open a document or another shortcut while writing or editing a file?
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/UX/Patterns/Drawer

**Comment by ferndot** [comment]
That sounds great, maybe we could use it as a quick way to switch between files.

Assigning to you if that is ok.

**Comment by HR** [comment]
Where about should I write the drawer code (<section id="drawer" role="region">) in index.html?

**Comment by ferndot** [comment]
Before the edit region would be best (I'm assuming that that's where the panel will be).

**Comment by HR** [comment]
How can I edit the toolbar universally (for the area/interface where you edit the text) to contain the sidebar?

**Comment by ferndot** [comment]
You can just change the back button in the edit section of index.html (ln. 151).

Make it activate the sidebar `onClick`, and change its `icon-back` class to `icon-menu`.

**Comment by HR** [comment]
In the doc it doesn't say how to activate the sidebar via js, so how can you do that?

**Comment by ferndot** [comment]
I would do something similar to what the nav/document.hashchange function (firetext.js ln.31) does, just without changing the hash.

**Comment by HR** [comment]
I am just currently working on a function to activate the sidebar

**Comment by ferndot** [comment]
Great!

**Comment by HR** [comment]
I'll finish it by tomorrow evening probably (lots of work at my job to do) but I'll finish it, so you guys work on other things and probs. have a nice day

**Comment by ferndot** [comment]
Ok, thanks for your help, and I hope your work goes well :)

**Comment by ferndot** [comment]
Finished with these commits: https://github.com/Joshua-S/FireText/commit/1f324520875d681b28d9f5d448aa96a05c00c7da, https://github.com/Joshua-S/FireText/commit/7862169273667367e9c487f815797822dfd9b849, https://github.com/Joshua-S/FireText/commit/b97f4fb5fe795e3efcbd76baa0968a464a8fff1f.
