### ISSUE TITLE
Firetext Release

### ISSUE THREAD

**Issue by logan-r** [codexa/firetext#91]
Just checked http://marketplace.firefox.com/app/firetext and it still hasn't been released. Anybody know about how long it will take?

**Comment by HR** [comment]
It currently says <b>Queue position: 19 of 215</b> , I mailed the and they replied:

<blockquote>
Hi, 
<br/>
it should be reviewed within the next week.
<br />
Andrew Williamson
<br />
Addons Technical Editor @ Addons.Mozilla.Org</blockquote>

**Comment by logan-r** [comment]
Great!
