### ISSUE TITLE
App has been rejected by a Firefox Marketplace reviewer

### ISSUE THREAD

**Issue by HR** [codexa/firetext#92]
I just checked and saw this shocking status: "<b>This app has been rejected by a Firefox Marketplace reviewer.</b>"
Here is the massage by reviewer:

Reviewed by Lisa Brewster (48 minutes ago)

<blockquote>
My sincere apologies for the delay, but I'm afraid we still can't publish an app that doesn't work. But what I CAN do is prioritize your review when you resubmit. Email me at adora@mozilla.com and I'll make sure you're taken care of. PS: Your app looks great, I'm excited to see it in its full glory!"
</blockquote>

**Comment by ferndot** [comment]
It was rejected because of the deviceStorage changes.  They were made after we released it, so it isn't our fault and it was fixed in 0.2.  She tested on a device running 1.0.1 which is incompatible with 0.1.

**Comment by HR** [comment]
So should we release v0.2 or v0.1 with the deviceStorage changes

**Comment by ferndot** [comment]
I think we should wait, and release 0.2 (it is due in the next week, and I already fixed the issue).  We can get a quick review because she is prioritizing it.

**Comment by HR** [comment]
Ok

**Comment by Graeme22** [comment]
it’s a bummer it was rejected. so we're waiting until v0.2 to re-submit it?

**Comment by HR** [comment]
yup

**Comment by ferndot** [comment]
Yes, unless we want to do a quick patch to 0.1.  But it doesn't really seem worth it because we are releasing 0.2 within a week.
