### ISSUE TITLE
Support wiki

### ISSUE THREAD

**Issue by ferndot** [codexa/firetext#95]
The wiki is located at http://firetext.codexa.org/support.
### Articles needed
- [ ] UI Demo (for first timers)
- [ ] Open a document
- [ ] Delete a document
- [ ] Save your work
- [ ] Format text
- [ ] Insert a list
- [ ] View the source of a HTML file
- [ ] Start Zen mode
- [ ] Connect with Dropbox
- [ ] Disable autosave
- [ ] Always edit in Zen mode
- [ ] Load the last open file on startup

**Comment by HR** [comment]
Autosave will be in save your work

**Comment by ferndot** [comment]
+1, but disabling autosave will be separate.  Note that autosave is now enabled by default.

**Comment by HR** [comment]
It is still part of Autosaving

**Comment by HR** [comment]
Changed page to "Manual and Autosave"

**Comment by HR** [comment]
color hex code please for highlighting the elements in screenshots

**Comment by ferndot** [comment]
The color that my mac used is #28A8FD.

**Comment by HR** [comment]
thanks

**Comment by logan-r** [comment]
Should we include a copy of the wiki inside the app?

**Comment by HR** [comment]
Yup, we should

**Comment by ferndot** [comment]
We could just have a link.  Let me commit something to let you see how it would work if we did it that way.

**Comment by ferndot** [comment]
Hmm, the Github site is not responsive.  I'm gonna port the wiki to codexa.co.nf.

**Comment by HR** [comment]
We'll have to redo this for new ui

**Comment by ferndot** [comment]
Yes, mockups of the site would be nice if you have time.

**Comment by ferndot** [comment]
Closing because we no longer have a domain for the wiki.  Will re-open, or create a new issue when that happens.
